import { db } from '../src/lib/db'

// Helper: tạo vocab entry với level + difficulty tự động
function V(level: string, word: string, phonetic: string, pos: string, def: string, ex: string, vi: string, cat: string) {
  const difficultyMap: Record<string, number> = { A0: 1, A1: 1, A2: 2, B1: 2, B2: 3, C1: 4, C2: 5 }
  return {
    id: `${level}_${word.toLowerCase().replace(/[^a-z0-9]/g, '_')}`,
    word,
    phonetic,
    partOfSpeech: pos,
    definition: def,
    example: ex,
    translation: vi,
    category: cat,
    level,
    difficulty: difficultyMap[level] || 1,
  }
}

async function main() {
  console.log('Seeding 700 vocabulary words by CEFR level...')

  const vocabs: any[] = []

  // ============================================================
  // A0 — PRE-BEGINNER (100 từ cơ bản nhất)
  // Số, màu, ngày, gia đình, đồ vật cơ bản, động từ thường
  // ============================================================
  const A0 = [
    ['one', '/wʌn/', 'number', 'số 1', 'I have one book.', 'một', 'general'],
    ['two', '/tuː/', 'number', 'số 2', 'She has two cats.', 'hai', 'general'],
    ['three', '/θriː/', 'number', 'số 3', 'Three apples are on the table.', 'ba', 'general'],
    ['four', '/fɔːr/', 'number', 'số 4', 'Four people are waiting.', 'bốn', 'general'],
    ['five', '/faɪv/', 'number', 'số 5', 'Give me five minutes.', 'năm', 'general'],
    ['six', '/sɪks/', 'number', 'số 6', 'Six students are absent.', 'sáu', 'general'],
    ['seven', '/ˈsev.ən/', 'number', 'số 7', 'Seven days in a week.', 'bảy', 'general'],
    ['eight', '/eɪt/', 'number', 'số 8', 'Eight hours of sleep.', 'tám', 'general'],
    ['nine', '/naɪn/', 'number', 'số 9', 'Nine players on a team.', 'chín', 'general'],
    ['ten', '/ten/', 'number', 'số 10', 'Ten fingers on my hands.', 'mười', 'general'],
    ['red', '/red/', 'adj', 'màu đỏ', 'The apple is red.', 'đỏ', 'general'],
    ['blue', '/bluː/', 'adj', 'màu xanh dương', 'The sky is blue.', 'xanh dương', 'general'],
    ['green', '/ɡriːn/', 'adj', 'màu xanh lá', 'The grass is green.', 'xanh lá', 'general'],
    ['yellow', '/ˈjel.əʊ/', 'adj', 'màu vàng', 'The sun is yellow.', 'vàng', 'general'],
    ['black', '/blæk/', 'adj', 'màu đen', 'My hair is black.', 'đen', 'general'],
    ['white', '/waɪt/', 'adj', 'màu trắng', 'The snow is white.', 'trắng', 'general'],
    ['big', '/bɪɡ/', 'adj', 'to, lớn', 'An elephant is big.', 'to, lớn', 'general'],
    ['small', '/smɔːl/', 'adj', 'nhỏ', 'A mouse is small.', 'nhỏ', 'general'],
    ['good', '/ɡʊd/', 'adj', 'tốt', 'This is a good book.', 'tốt', 'general'],
    ['bad', '/bæd/', 'adj', 'xấu, tệ', 'The weather is bad today.', 'xấu, tệ', 'general'],
    ['new', '/njuː/', 'adj', 'mới', 'I have a new phone.', 'mới', 'general'],
    ['old', '/əʊld/', 'adj', 'cũ, già', 'This house is old.', 'cũ, già', 'general'],
    ['happy', '/ˈhæp.i/', 'adj', 'vui, hạnh phúc', 'She is happy today.', 'vui, hạnh phúc', 'general'],
    ['sad', '/sæd/', 'adj', 'buồn', 'He looks sad.', 'buồn', 'general'],
    ['hot', '/hɒt/', 'adj', 'nóng', 'The coffee is hot.', 'nóng', 'general'],
    ['cold', '/kəʊld/', 'adj', 'lạnh', 'The water is cold.', 'lạnh', 'general'],
    ['eat', '/iːt/', 'verb', 'ăn', 'I eat breakfast at 7.', 'ăn', 'general'],
    ['drink', '/drɪŋk/', 'verb', 'uống', 'She drinks water.', 'uống', 'general'],
    ['go', '/ɡəʊ/', 'verb', 'đi', 'I go to school.', 'đi', 'general'],
    ['come', '/kʌm/', 'verb', 'đến', 'Please come here.', 'đến', 'general'],
    ['see', '/siː/', 'verb', 'nhìn thấy', 'I see a bird.', 'nhìn thấy', 'general'],
    ['hear', '/hɪər/', 'verb', 'nghe', 'I hear a noise.', 'nghe', 'general'],
    ['speak', '/spiːk/', 'verb', 'nói', 'She speaks English.', 'nói', 'general'],
    ['read', '/riːd/', 'verb', 'đọc', 'I read a book.', 'đọc', 'general'],
    ['write', '/raɪt/', 'verb', 'viết', 'He writes a letter.', 'viết', 'general'],
    ['run', '/rʌn/', 'verb', 'chạy', 'They run fast.', 'chạy', 'general'],
    ['walk', '/wɔːk/', 'verb', 'đi bộ', 'We walk to the park.', 'đi bộ', 'general'],
    ['sit', '/sɪt/', 'verb', 'ngồi', 'Please sit down.', 'ngồi', 'general'],
    ['stand', '/stænd/', 'verb', 'đứng', 'Please stand up.', 'đứng', 'general'],
    ['mother', '/ˈmʌð.ər/', 'noun', 'mẹ', 'My mother is kind.', 'mẹ', 'general'],
    ['father', '/ˈfɑː.ðər/', 'noun', 'cha', 'My father works hard.', 'cha', 'general'],
    ['brother', '/ˈbrʌð.ər/', 'noun', 'anh, em trai', 'My brother is tall.', 'anh, em trai', 'general'],
    ['sister', '/ˈsɪs.tər/', 'noun', 'chị, em gái', 'My sister is young.', 'chị, em gái', 'general'],
    ['son', '/sʌn/', 'noun', 'con trai', 'Their son is five.', 'con trai', 'general'],
    ['daughter', '/ˈdɔː.tər/', 'noun', 'con gái', 'Her daughter is cute.', 'con gái', 'general'],
    ['friend', '/frend/', 'noun', 'bạn bè', 'He is my friend.', 'bạn bè', 'general'],
    ['man', '/mæn/', 'noun', 'đàn ông', 'A man is at the door.', 'đàn ông', 'general'],
    ['woman', '/ˈwʊm.ən/', 'noun', 'phụ nữ', 'A woman is waiting.', 'phụ nữ', 'general'],
    ['boy', '/bɔɪ/', 'noun', 'con trai', 'The boy is playing.', 'con trai', 'general'],
    ['girl', '/ɡɜːl/', 'noun', 'con gái', 'The girl is reading.', 'con gái', 'general'],
    ['book', '/bʊk/', 'noun', 'sách', 'I read a book.', 'sách', 'general'],
    ['pen', '/pen/', 'noun', 'bút', 'This is my pen.', 'bút', 'general'],
    ['table', '/ˈteɪ.bəl/', 'noun', 'bàn', 'The book is on the table.', 'bàn', 'general'],
    ['chair', '/tʃeər/', 'noun', 'ghế', 'Please sit on the chair.', 'ghế', 'general'],
    ['house', '/haʊs/', 'noun', 'nhà', 'My house is big.', 'nhà', 'general'],
    ['door', '/dɔːr/', 'noun', 'cửa', 'Open the door, please.', 'cửa', 'general'],
    ['window', '/ˈwɪn.dəʊ/', 'noun', 'cửa sổ', 'The window is open.', 'cửa sổ', 'general'],
    ['car', '/kɑːr/', 'noun', 'xe hơi', 'His car is new.', 'xe hơi', 'general'],
    ['dog', '/dɒɡ/', 'noun', 'chó', 'The dog is barking.', 'chó', 'general'],
    ['cat', '/kæt/', 'noun', 'mèo', 'The cat is sleeping.', 'mèo', 'general'],
    ['water', '/ˈwɔː.tər/', 'noun', 'nước', 'I drink water.', 'nước', 'general'],
    ['food', '/fuːd/', 'noun', 'thức ăn', 'The food is good.', 'thức ăn', 'general'],
    ['milk', '/mɪlk/', 'noun', 'sữa', 'I drink milk every morning.', 'sữa', 'general'],
    ['bread', '/bred/', 'noun', 'bánh mì', 'She eats bread.', 'bánh mì', 'general'],
    ['apple', '/ˈæp.əl/', 'noun', 'quả táo', 'An apple a day.', 'quả táo', 'general'],
    ['rice', '/raɪs/', 'noun', 'cơm, gạo', 'We eat rice.', 'cơm, gạo', 'general'],
    ['Monday', '/ˈmʌn.deɪ/', 'noun', 'thứ Hai', 'Today is Monday.', 'thứ Hai', 'general'],
    ['Tuesday', '/ˈtjuːz.deɪ/', 'noun', 'thứ Ba', 'I work on Tuesday.', 'thứ Ba', 'general'],
    ['Wednesday', '/ˈwenz.deɪ/', 'noun', 'thứ Tư', 'See you Wednesday.', 'thứ Tư', 'general'],
    ['Thursday', '/ˈθɜːz.deɪ/', 'noun', 'thứ Năm', 'Thursday is busy.', 'thứ Năm', 'general'],
    ['Friday', '/ˈfraɪ.deɪ/', 'noun', 'thứ Sáu', 'Friday is fun.', 'thứ Sáu', 'general'],
    ['Saturday', '/ˈsæt.ə.deɪ/', 'noun', 'thứ Bảy', 'Saturday is free.', 'thứ Bảy', 'general'],
    ['Sunday', '/ˈsʌn.deɪ/', 'noun', 'Chủ Nhật', 'Sunday is relaxing.', 'Chủ Nhật', 'general'],
    ['day', '/deɪ/', 'noun', 'ngày', 'Have a nice day.', 'ngày', 'general'],
    ['week', '/wiːk/', 'noun', 'tuần', 'See you next week.', 'tuần', 'general'],
    ['month', '/mʌnθ/', 'noun', 'tháng', 'January is a cold month.', 'tháng', 'general'],
    ['year', '/jɪər/', 'noun', 'năm', 'A year has twelve months.', 'năm', 'general'],
    ['today', '/təˈdeɪ/', 'adv', 'hôm nay', 'I am busy today.', 'hôm nay', 'general'],
    ['tomorrow', '/təˈmɒr.əʊ/', 'adv', 'ngày mai', 'See you tomorrow.', 'ngày mai', 'general'],
    ['yesterday', '/ˈjes.tə.deɪ/', 'adv', 'hôm qua', 'I saw him yesterday.', 'hôm qua', 'general'],
    ['hello', '/həˈləʊ/', 'exclamation', 'xin chào', 'Hello, how are you?', 'xin chào', 'general'],
    ['goodbye', '/ˌɡʊdˈbaɪ/', 'exclamation', 'tạm biệt', 'Goodbye, see you soon.', 'tạm biệt', 'general'],
    ['yes', '/jes/', 'adv', 'có, vâng', 'Yes, I agree.', 'có, vâng', 'general'],
    ['no', '/nəʊ/', 'adv', 'không', 'No, thank you.', 'không', 'general'],
    ['please', '/pliːz/', 'adv', 'làm ơn', 'Help me, please.', 'làm ơn', 'general'],
    ['thanks', '/θæŋks/', 'noun', 'cảm ơn', 'Thanks for your help.', 'cảm ơn', 'general'],
    ['love', '/lʌv/', 'verb', 'yêu', 'I love my family.', 'yêu', 'general'],
    ['like', '/laɪk/', 'verb', 'thích', 'I like coffee.', 'thích', 'general'],
    ['want', '/wɒnt/', 'verb', 'muốn', 'I want to go home.', 'muốn', 'general'],
    ['need', '/niːd/', 'verb', 'cần', 'I need help.', 'cần', 'general'],
    ['have', '/hæv/', 'verb', 'có', 'I have a car.', 'có', 'general'],
    ['make', '/meɪk/', 'verb', 'làm, tạo', 'She makes a cake.', 'làm, tạo', 'general'],
    ['do', '/duː/', 'verb', 'làm', 'What do you do?', 'làm', 'general'],
    ['play', '/pleɪ/', 'verb', 'chơi', 'Children play outside.', 'chơi', 'general'],
    ['work', '/wɜːk/', 'verb', 'làm việc', 'I work in an office.', 'làm việc', 'general'],
    ['sleep', '/sliːp/', 'verb', 'ngủ', 'I sleep eight hours.', 'ngủ', 'general'],
    ['morning', '/ˈmɔː.nɪŋ/', 'noun', 'buổi sáng', 'Good morning!', 'buổi sáng', 'general'],
    ['evening', '/ˈiːv.nɪŋ/', 'noun', 'buổi tối', 'Good evening!', 'buổi tối', 'general'],
    ['night', '/naɪt/', 'noun', 'ban đêm', 'Good night!', 'ban đêm', 'general'],
    ['time', '/taɪm/', 'noun', 'thời gian', 'What time is it?', 'thời gian', 'general'],
    ['home', '/həʊm/', 'noun', 'nhà', 'I go home at 6.', 'nhà', 'general'],
    ['school', '/skuːl/', 'noun', 'trường học', 'My school is near.', 'trường học', 'general'],
    ['money', '/ˈmʌn.i/', 'noun', 'tiền', 'I need money.', 'tiền', 'general'],
    ['help', '/help/', 'verb', 'giúp', 'Can you help me?', 'giúp', 'general'],
  ]
  A0.forEach((w) => vocabs.push(V('A0', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // ============================================================
  // A1 — ELEMENTARY (100 từ)
  // Giao tiếp cơ bản, từ vựng đời sống hàng ngày
  // ============================================================
  const A1 = [
    ['family', '/ˈfæm.əl.i/', 'noun', 'gia đình', 'My family is large.', 'gia đình', 'general'],
    ['people', '/ˈpiː.pəl/', 'noun', 'người, mọi người', 'Many people are here.', 'người, mọi người', 'general'],
    ['child', '/tʃaɪld/', 'noun', 'đứa trẻ', 'The child is happy.', 'đứa trẻ', 'general'],
    ['baby', '/ˈbeɪ.bi/', 'noun', 'em bé', 'The baby is sleeping.', 'em bé', 'general'],
    ['teacher', '/ˈtiː.tʃər/', 'noun', 'giáo viên', 'My teacher is kind.', 'giáo viên', 'general'],
    ['student', '/ˈstjuː.dənt/', 'noun', 'học sinh, sinh viên', 'She is a student.', 'học sinh, sinh viên', 'general'],
    ['doctor', '/ˈdɒk.tər/', 'noun', 'bác sĩ', 'The doctor is busy.', 'bác sĩ', 'general'],
    ['name', '/neɪm/', 'noun', 'tên', 'What is your name?', 'tên', 'general'],
    ['age', '/eɪdʒ/', 'noun', 'tuổi', 'What is your age?', 'tuổi', 'general'],
    ['city', '/ˈsɪt.i/', 'noun', 'thành phố', 'I live in a big city.', 'thành phố', 'general'],
    ['country', '/ˈkʌn.tri/', 'noun', 'quốc gia', 'Vietnam is my country.', 'quốc gia', 'general'],
    ['street', '/striːt/', 'noun', 'đường phố', 'The street is busy.', 'đường phố', 'general'],
    ['shop', '/ʃɒp/', 'noun', 'cửa hàng', 'The shop is open.', 'cửa hàng', 'general'],
    ['park', '/pɑːk/', 'noun', 'công viên', 'We go to the park.', 'công viên', 'general'],
    ['office', '/ˈɒf.ɪs/', 'noun', 'văn phòng', 'My office is downtown.', 'văn phòng', 'office'],
    ['job', '/dʒɒb/', 'noun', 'công việc', 'I have a new job.', 'công việc', 'office'],
    ['lunch', '/lʌntʃ/', 'noun', 'bữa trưa', 'We have lunch at noon.', 'bữa trưa', 'general'],
    ['dinner', '/ˈdɪn.ər/', 'noun', 'bữa tối', 'Dinner is ready.', 'bữa tối', 'general'],
    ['breakfast', '/ˈbrek.fəst/', 'noun', 'bữa sáng', 'I eat breakfast early.', 'bữa sáng', 'general'],
    ['coffee', '/ˈkɒf.i/', 'noun', 'cà phê', 'I drink coffee every day.', 'cà phê', 'general'],
    ['tea', '/tiː/', 'noun', 'trà', 'She likes green tea.', 'trà', 'general'],
    ['sugar', '/ˈʃʊɡ.ər/', 'noun', 'đường', 'No sugar, please.', 'đường', 'general'],
    ['salt', '/sɒlt/', 'noun', 'muối', 'Add some salt.', 'muối', 'general'],
    ['egg', '/eɡ/', 'noun', 'quả trứng', 'I eat an egg.', 'quả trứng', 'general'],
    ['meat', '/miːt/', 'noun', 'thịt', 'He does not eat meat.', 'thịt', 'general'],
    ['fish', '/fɪʃ/', 'noun', 'cá', 'We eat fish.', 'cá', 'general'],
    ['fruit', '/fruːt/', 'noun', 'trái cây', 'Fruit is healthy.', 'trái cây', 'general'],
    ['vegetable', '/ˈvedʒ.tə.bəl/', 'noun', 'rau', 'I eat vegetables.', 'rau', 'general'],
    ['clothes', '/kləʊðz/', 'noun', 'quần áo', 'My clothes are clean.', 'quần áo', 'general'],
    ['shoe', '/ʃuː/', 'noun', 'giày', 'My shoes are new.', 'giày', 'general'],
    ['hat', '/hæt/', 'noun', 'mũ', 'He wears a hat.', 'mũ', 'general'],
    ['bag', '/bæɡ/', 'noun', 'túi', 'This is my bag.', 'túi', 'general'],
    ['phone', '/fəʊn/', 'noun', 'điện thoại', 'My phone is ringing.', 'điện thoại', 'tech'],
    ['computer', '/kəmˈpjuː.tər/', 'noun', 'máy tính', 'I use a computer.', 'máy tính', 'tech'],
    ['key', '/kiː/', 'noun', 'chìa khóa', 'Where is my key?', 'chìa khóa', 'general'],
    ['clock', '/klɒk/', 'noun', 'đồng hồ', 'The clock is on the wall.', 'đồng hồ', 'general'],
    ['watch', '/wɒtʃ/', 'noun', 'đồng hồ đeo tay', 'My watch is broken.', 'đồng hồ đeo tay', 'general'],
    ['picture', '/ˈpɪk.tʃər/', 'noun', 'bức tranh', 'The picture is beautiful.', 'bức tranh', 'general'],
    ['letter', '/ˈlet.ər/', 'noun', 'lá thư', 'I write a letter.', 'lá thư', 'general'],
    ['question', '/ˈkwes.tʃən/', 'noun', 'câu hỏi', 'I have a question.', 'câu hỏi', 'general'],
    ['answer', '/ˈɑːn.sər/', 'noun', 'câu trả lời', 'What is the answer?', 'câu trả lời', 'general'],
    ['problem', '/ˈprɒb.ləm/', 'noun', 'vấn đề', 'We have a problem.', 'vấn đề', 'general'],
    ['idea', '/aɪˈdɪə/', 'noun', 'ý tưởng', 'Good idea!', 'ý tưởng', 'general'],
    ['story', '/ˈstɔː.ri/', 'noun', 'câu chuyện', 'Tell me a story.', 'câu chuyện', 'general'],
    ['song', '/sɒŋ/', 'noun', 'bài hát', 'This song is nice.', 'bài hát', 'general'],
    ['game', '/ɡeɪm/', 'noun', 'trò chơi', 'We play a game.', 'trò chơi', 'general'],
    ['sport', '/spɔːt/', 'noun', 'thể thao', 'I like sport.', 'thể thao', 'general'],
    ['ball', '/bɔːl/', 'noun', 'quả bóng', 'The ball is round.', 'quả bóng', 'general'],
    ['color', '/ˈkʌl.ər/', 'noun', 'màu sắc', 'What color is it?', 'màu sắc', 'general'],
    ['number', '/ˈnʌm.bər/', 'noun', 'số', 'What is your phone number?', 'số', 'general'],
    ['price', '/praɪs/', 'noun', 'giá tiền', 'What is the price?', 'giá tiền', 'finance'],
    ['buy', '/baɪ/', 'verb', 'mua', 'I buy bread.', 'mua', 'general'],
    ['sell', '/sel/', 'verb', 'bán', 'They sell flowers.', 'bán', 'general'],
    ['pay', '/peɪ/', 'verb', 'trả tiền', 'I pay the bill.', 'trả tiền', 'finance'],
    ['open', '/ˈəʊ.pən/', 'verb', 'mở', 'Open the door.', 'mở', 'general'],
    ['close', '/kləʊz/', 'verb', 'đóng', 'Close the window.', 'đóng', 'general'],
    ['start', '/stɑːt/', 'verb', 'bắt đầu', 'The class starts at 9.', 'bắt đầu', 'general'],
    ['stop', '/stɒp/', 'verb', 'dừng', 'Stop the car.', 'dừng', 'general'],
    ['give', '/ɡɪv/', 'verb', 'cho', 'Give me the book.', 'cho', 'general'],
    ['take', '/teɪk/', 'verb', 'lấy', 'Take this pen.', 'lấy', 'general'],
    ['put', '/pʊt/', 'verb', 'đặt, để', 'Put it on the table.', 'đặt, để', 'general'],
    ['get', '/ɡet/', 'verb', 'nhận, lấy được', 'I get an email.', 'nhận, lấy được', 'general'],
    ['find', '/faɪnd/', 'verb', 'tìm thấy', 'I find my keys.', 'tìm thấy', 'general'],
    ['lose', '/luːz/', 'verb', 'mất, làm rơi', 'I lose my phone.', 'mất, làm rơi', 'general'],
    ['think', '/θɪŋk/', 'verb', 'nghĩ', 'I think so.', 'nghĩ', 'general'],
    ['know', '/nəʊ/', 'verb', 'biết', 'I know the answer.', 'biết', 'general'],
    ['understand', '/ˌʌn.dəˈstænd/', 'verb', 'hiểu', 'I understand you.', 'hiểu', 'general'],
    ['remember', '/rɪˈmem.bər/', 'verb', 'nhớ', 'I remember her name.', 'nhớ', 'general'],
    ['forget', '/fəˈɡet/', 'verb', 'quên', 'I forget the password.', 'quên', 'general'],
    ['learn', '/lɜːn/', 'verb', 'học', 'I learn English.', 'học', 'general'],
    ['teach', '/tiːtʃ/', 'verb', 'dạy', 'She teaches math.', 'dạy', 'general'],
    ['ask', '/ɑːsk/', 'verb', 'hỏi', 'Ask the teacher.', 'hỏi', 'general'],
    ['tell', '/tel/', 'verb', 'kể, bảo', 'Tell me the truth.', 'kể, bảo', 'general'],
    ['say', '/seɪ/', 'verb', 'nói', 'What did he say?', 'nói', 'general'],
    ['show', '/ʃəʊ/', 'verb', 'cho xem', 'Show me the way.', 'cho xem', 'general'],
    ['call', '/kɔːl/', 'verb', 'gọi điện', 'Call me later.', 'gọi điện', 'general'],
    ['try', '/traɪ/', 'verb', 'thử', 'Try again.', 'thử', 'general'],
    ['use', '/juːz/', 'verb', 'sử dụng', 'I use a computer.', 'sử dụng', 'general'],
    ['live', '/lɪv/', 'verb', 'sống', 'I live in Hanoi.', 'sống', 'general'],
    ['look', '/lʊk/', 'verb', 'nhìn', 'Look at this!', 'nhìn', 'general'],
    ['listen', '/ˈlɪs.ən/', 'verb', 'lắng nghe', 'Listen to me.', 'lắng nghe', 'general'],
    ['wait', '/weɪt/', 'verb', 'chờ đợi', 'Wait a minute.', 'chờ đợi', 'general'],
    ['meet', '/miːt/', 'verb', 'gặp gỡ', 'Let us meet at 5.', 'gặp gỡ', 'general'],
    ['send', '/send/', 'verb', 'gửi', 'Send me an email.', 'gửi', 'office'],
    ['bring', '/brɪŋ/', 'verb', 'mang đến', 'Bring your book.', 'mang đến', 'general'],
    ['fast', '/fɑːst/', 'adj', 'nhanh', 'He is fast.', 'nhanh', 'general'],
    ['slow', '/sləʊ/', 'adj', 'chậm', 'The bus is slow.', 'chậm', 'general'],
    ['easy', '/ˈiː.zi/', 'adj', 'dễ', 'The test is easy.', 'dễ', 'general'],
    ['hard', '/hɑːd/', 'adj', 'khó, cứng', 'This question is hard.', 'khó, cứng', 'general'],
    ['clean', '/kliːn/', 'adj', 'sạch sẽ', 'The room is clean.', 'sạch sẽ', 'general'],
    ['dirty', '/ˈdɜː.ti/', 'adj', 'bẩn', 'My hands are dirty.', 'bẩn', 'general'],
    ['open', '/ˈəʊ.pən/', 'adj', 'mở, mở cửa', 'The shop is open.', 'mở, mở cửa', 'general'],
    ['closed', '/kləʊzd/', 'adj', 'đóng cửa', 'The bank is closed.', 'đóng cửa', 'general'],
    ['full', '/fʊl/', 'adj', 'đầy', 'The glass is full.', 'đầy', 'general'],
    ['empty', '/ˈem.ti/', 'adj', 'trống rỗng', 'The box is empty.', 'trống rỗng', 'general'],
    ['beautiful', '/ˈbjuː.tɪ.fəl/', 'adj', 'đẹp', 'She is beautiful.', 'đẹp', 'general'],
    ['important', '/ɪmˈpɔː.tənt/', 'adj', 'quan trọng', 'Family is important.', 'quan trọng', 'general'],
    ['here', '/hɪər/', 'adv', 'ở đây', 'Come here.', 'ở đây', 'general'],
    ['there', '/ðeər/', 'adv', 'ở đó', 'It is there.', 'ở đó', 'general'],
    ['now', '/naʊ/', 'adv', 'bây giờ', 'Do it now.', 'bây giờ', 'general'],
    ['very', '/ˈver.i/', 'adv', 'rất', 'She is very kind.', 'rất', 'general'],
    ['always', '/ˈɔːl.weɪz/', 'adv', 'luôn luôn', 'I always wake up early.', 'luôn luôn', 'general'],
    ['never', '/ˈnev.ər/', 'adv', 'không bao giờ', 'I never smoke.', 'không bao giờ', 'general'],
  ]
  A1.forEach((w) => vocabs.push(V('A1', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // ============================================================
  // A2 — PRE-INTERMEDIATE (100 từ)
  // Du lịch, mua sắm, giao tiếp xã hội
  // ============================================================
  const A2 = [
    ['airport', '/ˈeə.pɔːt/', 'noun', 'sân bay', 'The airport is far.', 'sân bay', 'travel'],
    ['ticket', '/ˈtɪk.ɪt/', 'noun', 'vé', 'Buy a ticket.', 'vé', 'travel'],
    ['passport', '/ˈpɑːs.pɔːt/', 'noun', 'hộ chiếu', 'Show your passport.', 'hộ chiếu', 'travel'],
    ['luggage', '/ˈlʌɡ.ɪdʒ/', 'noun', 'hành lý', 'My luggage is heavy.', 'hành lý', 'travel'],
    ['flight', '/flaɪt/', 'noun', 'chuyến bay', 'The flight is delayed.', 'chuyến bay', 'travel'],
    ['hotel', '/həʊˈtel/', 'noun', 'khách sạn', 'Book a hotel.', 'khách sạn', 'travel'],
    ['room', '/ruːm/', 'noun', 'phòng', 'My room is nice.', 'phòng', 'travel'],
    ['restaurant', '/ˈres.trɒnt/', 'noun', 'nhà hàng', 'We eat at a restaurant.', 'nhà hàng', 'travel'],
    ['menu', '/ˈmen.juː/', 'noun', 'thực đơn', 'Can I see the menu?', 'thực đơn', 'travel'],
    ['waiter', '/ˈweɪ.tər/', 'noun', 'bồi bàn', 'The waiter is coming.', 'bồi bàn', 'travel'],
    ['bill', '/bɪl/', 'noun', 'hóa đơn', 'Can I have the bill?', 'hóa đơn', 'finance'],
    ['map', '/mæp/', 'noun', 'bản đồ', 'Look at the map.', 'bản đồ', 'travel'],
    ['way', '/weɪ/', 'noun', 'đường, cách', 'Which way?', 'đường, cách', 'general'],
    ['road', '/rəʊd/', 'noun', 'con đường', 'The road is long.', 'con đường', 'general'],
    ['station', '/ˈsteɪ.ʃən/', 'noun', 'ga, trạm', 'The station is near.', 'ga, trạm', 'travel'],
    ['bus', '/bʌs/', 'noun', 'xe buýt', 'Take the bus.', 'xe buýt', 'travel'],
    ['train', '/treɪn/', 'noun', 'tàu hỏa', 'The train is late.', 'tàu hỏa', 'travel'],
    ['taxi', '/ˈtæk.si/', 'noun', 'xe tắc xi', 'Call a taxi.', 'xe tắc xi', 'travel'],
    ['map', '/mæp/', 'noun', 'bản đồ', 'Check the map.', 'bản đồ', 'travel'],
    ['weather', '/ˈweð.ər/', 'noun', 'thời tiết', 'The weather is nice.', 'thời tiết', 'general'],
    ['rain', '/reɪn/', 'noun', 'mưa', 'The rain is heavy.', 'mưa', 'general'],
    ['snow', '/snəʊ/', 'noun', 'tuyết', 'The snow is white.', 'tuyết', 'general'],
    ['wind', '/wɪnd/', 'noun', 'gió', 'The wind is strong.', 'gió', 'general'],
    ['sun', '/sʌn/', 'noun', 'mặt trời', 'The sun is bright.', 'mặt trời', 'general'],
    ['cloud', '/klaʊd/', 'noun', 'mây', 'The sky has clouds.', 'mây', 'general'],
    ['season', '/ˈsiː.zən/', 'noun', 'mùa', 'Summer is my favorite season.', 'mùa', 'general'],
    ['spring', '/sprɪŋ/', 'noun', 'mùa xuân', 'Spring is warm.', 'mùa xuân', 'general'],
    ['summer', '/ˈsʌm.ər/', 'noun', 'mùa hạ', 'Summer is hot.', 'mùa hạ', 'general'],
    ['autumn', '/ˈɔː.təm/', 'noun', 'mùa thu', 'Autumn is cool.', 'mùa thu', 'general'],
    ['winter', '/ˈwɪn.tər/', 'noun', 'mùa đông', 'Winter is cold.', 'mùa đông', 'general'],
    ['holiday', '/ˈhɒl.ə.deɪ/', 'noun', 'kỳ nghỉ', 'We go on holiday.', 'kỳ nghỉ', 'travel'],
    ['trip', '/trɪp/', 'noun', 'chuyến đi', 'Have a nice trip!', 'chuyến đi', 'travel'],
    ['travel', '/ˈtræv.əl/', 'verb', 'du lịch', 'I love to travel.', 'du lịch', 'travel'],
    ['visit', '/ˈvɪz.ɪt/', 'verb', 'thăm quan', 'We visit the museum.', 'thăm quan', 'travel'],
    ['arrive', '/əˈraɪv/', 'verb', 'đến nơi', 'We arrive at 6.', 'đến nơi', 'travel'],
    ['leave', '/liːv/', 'verb', 'rời đi', 'We leave at 7.', 'rời đi', 'travel'],
    ['stay', '/steɪ/', 'verb', 'lưu trú', 'We stay at a hotel.', 'lưu trú', 'travel'],
    ['return', '/rɪˈtɜːn/', 'verb', 'trở về', 'I return home.', 'trở về', 'general'],
    ['expensive', '/ɪkˈspen.sɪv/', 'adj', 'đắt đỏ', 'The car is expensive.', 'đắt đỏ', 'finance'],
    ['cheap', '/tʃiːp/', 'adj', 'rẻ', 'The shirt is cheap.', 'rẻ', 'finance'],
    ['free', '/friː/', 'adj', 'miễn phí, rảnh', 'The ticket is free.', 'miễn phí, rảnh', 'general'],
    ['busy', '/ˈbɪz.i/', 'adj', 'bận rộn', 'I am busy today.', 'bận rộn', 'office'],
    ['ready', '/ˈred.i/', 'adj', 'sẵn sàng', 'Are you ready?', 'sẵn sàng', 'general'],
    ['sure', '/ʃʊər/', 'adj', 'chắc chắn', 'I am sure.', 'chắc chắn', 'general'],
    ['right', '/raɪt/', 'adj', 'đúng, bên phải', 'You are right.', 'đúng, bên phải', 'general'],
    ['wrong', '/rɒŋ/', 'adj', 'sai', 'The answer is wrong.', 'sai', 'general'],
    ['same', '/seɪm/', 'adj', 'giống nhau', 'We are the same age.', 'giống nhau', 'general'],
    ['different', '/ˈdɪf.ər.ənt/', 'adj', 'khác nhau', 'They are different.', 'khác nhau', 'general'],
    ['together', '/təˈɡeð.ər/', 'adv', 'cùng nhau', 'We work together.', 'cùng nhau', 'general'],
    ['again', '/əˈɡen/', 'adv', 'lần nữa', 'Try again.', 'lần nữa', 'general'],
    ['sometimes', '/ˈsʌm.taɪmz/', 'adv', 'đôi khi', 'I sometimes swim.', 'đôi khi', 'general'],
    ['usually', '/ˈjuː.ʒu.ə.li/', 'adv', 'thường xuyên', 'I usually wake up at 6.', 'thường xuyên', 'general'],
    ['often', '/ˈɒf.ən/', 'adv', 'thường', 'I often go there.', 'thường', 'general'],
    ['early', '/ˈɜː.li/', 'adv', 'sớm', 'I wake up early.', 'sớm', 'general'],
    ['late', '/leɪt/', 'adv', 'muộn', 'I am late.', 'muộn', 'general'],
    ['quickly', '/ˈkwɪk.li/', 'adv', 'nhanh chóng', 'Run quickly!', 'nhanh chóng', 'general'],
    ['slowly', '/ˈsləʊ.li/', 'adv', 'chậm rãi', 'Speak slowly, please.', 'chậm rãi', 'general'],
    ['well', '/wel/', 'adv', 'tốt', 'She sings well.', 'tốt', 'general'],
    ['better', '/ˈbet.ər/', 'adj', 'tốt hơn', 'This is better.', 'tốt hơn', 'general'],
    ['best', '/best/', 'adj', 'tốt nhất', 'She is the best.', 'tốt nhất', 'general'],
    ['more', '/mɔːr/', 'adv', 'hơn', 'I need more time.', 'hơn', 'general'],
    ['most', '/məʊst/', 'adv', 'hầu hết, nhất', 'Most people agree.', 'hầu hết, nhất', 'general'],
    ['much', '/mʌtʃ/', 'adv', 'nhiều', 'Thank you very much.', 'nhiều', 'general'],
    ['many', '/ˈmen.i/', 'adj', 'nhiều', 'Many people come.', 'nhiều', 'general'],
    ['few', '/fjuː/', 'adj', 'ít', 'Few people know.', 'ít', 'general'],
    ['little', '/ˈlɪt.l̩/', 'adj', 'ít, nhỏ', 'I have little time.', 'ít, nhỏ', 'general'],
    ['some', '/sʌm/', 'adj', 'một vài', 'I need some water.', 'một vài', 'general'],
    ['any', '/ˈen.i/', 'adj', 'nào, một ít', 'Is there any milk?', 'nào, một ít', 'general'],
    ['every', '/ˈev.ri/', 'adj', 'mỗi, mọi', 'I go every day.', 'mỗi, mọi', 'general'],
    ['each', '/iːtʃ/', 'adj', 'mỗi', 'Each student has a book.', 'mỗi', 'general'],
    ['all', '/ɔːl/', 'adj', 'tất cả', 'All students are here.', 'tất cả', 'general'],
    ['both', '/bəʊθ/', 'adj', 'cả hai', 'Both of them are tall.', 'cả hai', 'general'],
    ['another', '/əˈnʌð.ər/', 'adj', 'một khác', 'Give me another one.', 'một khác', 'general'],
    ['other', '/ˈʌð.ər/', 'adj', 'khác', 'Other people are coming.', 'khác', 'general'],
    ['such', '/sʌtʃ/', 'adj', 'như vậy', 'I never saw such a thing.', 'như vậy', 'general'],
    ['because', '/bɪˈkɒz/', 'conj', 'bởi vì', 'I am happy because you are here.', 'bởi vì', 'general'],
    ['but', '/bʌt/', 'conj', 'nhưng', 'I am tired but happy.', 'nhưng', 'general'],
    ['or', '/ɔːr/', 'conj', 'hoặc', 'Tea or coffee?', 'hoặc', 'general'],
    ['so', '/səʊ/', 'conj', 'vì vậy', 'I was tired, so I slept.', 'vì vậy', 'general'],
    ['if', '/ɪf/', 'conj', 'nếu', 'If it rains, I stay home.', 'nếu', 'general'],
    ['when', '/wen/', 'conj', 'khi', 'When I see her, I will tell her.', 'khi', 'general'],
    ['while', '/waɪl/', 'conj', 'trong khi', 'Wait while I work.', 'trong khi', 'general'],
    ['before', '/bɪˈfɔːr/', 'prep', 'trước khi', 'Wash hands before eating.', 'trước khi', 'general'],
    ['after', '/ˈɑːf.tər/', 'prep', 'sau khi', 'After lunch, I rest.', 'sau khi', 'general'],
    ['during', '/ˈdjʊə.rɪŋ/', 'prep', 'trong suốt', 'During the meeting, I took notes.', 'trong suốt', 'office'],
    ['between', '/bɪˈtwiːn/', 'prep', 'giữa (2)', 'Between you and me.', 'giữa (2)', 'general'],
    ['among', '/əˈmʌŋ/', 'prep', 'giữa (nhiều)', 'Among the books.', 'giữa (nhiều)', 'general'],
    ['through', '/θruː/', 'prep', 'xuyên qua', 'Walk through the door.', 'xuyên qua', 'general'],
    ['around', '/əˈraʊnd/', 'prep', 'xung quanh', 'Look around you.', 'xung quanh', 'general'],
    ['along', '/əˈlɒŋ/', 'prep', 'dọc theo', 'Walk along the street.', 'dọc theo', 'general'],
    ['across', '/əˈkrɒs/', 'prep', 'băng qua', 'Go across the bridge.', 'băng qua', 'general'],
    ['behind', '/bɪˈhaɪnd/', 'prep', 'phía sau', 'The cat is behind the door.', 'phía sau', 'general'],
    ['beside', '/bɪˈsaɪd/', 'prep', 'bên cạnh', 'Sit beside me.', 'bên cạnh', 'general'],
    ['above', '/əˈbʌv/', 'prep', 'phía trên', 'The plane is above the clouds.', 'phía trên', 'general'],
    ['below', '/bɪˈləʊ/', 'prep', 'phía dưới', 'The temperature is below zero.', 'phía dưới', 'general'],
    ['inside', '/ɪnˈsaɪd/', 'prep', 'bên trong', 'Come inside.', 'bên trong', 'general'],
    ['outside', '/ˌaʊtˈsaɪd/', 'prep', 'bên ngoài', 'Wait outside.', 'bên ngoài', 'general'],
    ['without', '/wɪˈðaʊt/', 'prep', 'không có', 'I cannot do it without you.', 'không có', 'general'],
    ['within', '/wɪˈðɪn/', 'prep', 'trong vòng', 'Finish within an hour.', 'trong vòng', 'office'],
    ['against', '/əˈɡenst/', 'prep', 'chống lại', 'I am against the plan.', 'chống lại', 'general'],
    ['about', '/əˈbaʊt/', 'prep', 'về, khoảng', 'Tell me about it.', 'về, khoảng', 'general'],
    ['should', '/ʃʊd/', 'verb', 'nên', 'You should rest.', 'nên', 'general'],
    ['could', '/kʊd/', 'verb', 'có thể (qk)', 'I could help you.', 'có thể (qk)', 'general'],
    ['would', '/wʊd/', 'verb', 'sẽ (giả định)', 'I would like tea.', 'sẽ (giả định)', 'general'],
    ['must', '/mʌst/', 'verb', 'phải', 'You must go now.', 'phải', 'office'],
    ['might', '/maɪt/', 'verb', 'có lẽ', 'It might rain.', 'có lẽ', 'general'],
  ]
  A2.forEach((w) => vocabs.push(V('A2', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // ============================================================
  // B1 — INTERMEDIATE (100 từ) — TOEIC 400-600
  // Business English cơ bản, văn phòng, họp hành
  // ============================================================
  const B1 = [
    ['meeting', '/ˈmiː.tɪŋ/', 'noun', 'cuộc họp', 'The meeting is at 10.', 'cuộc họp', 'office'],
    ['schedule', '/ˈʃed.juːl/', 'noun', 'lịch trình', 'Check the schedule.', 'lịch trình', 'office'],
    ['deadline', '/ˈded.laɪn/', 'noun', 'hạn chót', 'The deadline is Friday.', 'hạn chót', 'office'],
    ['colleague', '/ˈkɒl.iːɡ/', 'noun', 'đồng nghiệp', 'My colleague is helpful.', 'đồng nghiệp', 'office'],
    ['department', '/dɪˈpɑːt.mənt/', 'noun', 'phòng ban', 'Which department?', 'phòng ban', 'office'],
    ['manager', '/ˈmæn.ɪ.dʒər/', 'noun', 'quản lý', 'The manager is busy.', 'quản lý', 'office'],
    ['employee', '/ɪmˈplɔɪ.iː/', 'noun', 'nhân viên', 'He is an employee.', 'nhân viên', 'hr'],
    ['employer', '/ɪmˈplɔɪ.ər/', 'noun', 'người sử dụng lao động', 'The employer is fair.', 'người sử dụng lao động', 'hr'],
    ['boss', '/bɒs/', 'noun', 'sếp', 'My boss is strict.', 'sếp', 'office'],
    ['staff', '/stɑːf/', 'noun', 'nhân sự', 'The staff is friendly.', 'nhân sự', 'hr'],
    ['client', '/ˈklaɪ.ənt/', 'noun', 'khách hàng', 'The client is happy.', 'khách hàng', 'business'],
    ['customer', '/ˈkʌs.tə.mər/', 'noun', 'khách hàng', 'The customer is right.', 'khách hàng', 'business'],
    ['company', '/ˈkʌm.pə.ni/', 'noun', 'công ty', 'Our company is large.', 'công ty', 'business'],
    ['business', '/ˈbɪz.nɪs/', 'noun', 'kinh doanh', 'Business is good.', 'kinh doanh', 'business'],
    ['office', '/ˈɒf.ɪs/', 'noun', 'văn phòng', 'The office is quiet.', 'văn phòng', 'office'],
    ['report', '/rɪˈpɔːt/', 'noun', 'báo cáo', 'Write a report.', 'báo cáo', 'office'],
    ['presentation', '/ˌprez.ənˈteɪ.ʃən/', 'noun', 'bài thuyết trình', 'The presentation is long.', 'bài thuyết trình', 'office'],
    ['project', '/ˈprɒdʒ.ekt/', 'noun', 'dự án', 'The project is big.', 'dự án', 'office'],
    ['plan', '/plæn/', 'noun', 'kế hoạch', 'Make a plan.', 'kế hoạch', 'office'],
    ['goal', '/ɡəʊl/', 'noun', 'mục tiêu', 'Our goal is success.', 'mục tiêu', 'office'],
    ['target', '/ˈtɑː.ɡɪt/', 'noun', 'chỉ tiêu', 'Meet the target.', 'chỉ tiêu', 'office'],
    ['result', '/rɪˈzʌlt/', 'noun', 'kết quả', 'The result is good.', 'kết quả', 'office'],
    ['success', '/səkˈses/', 'noun', 'thành công', 'Success takes time.', 'thành công', 'business'],
    ['failure', '/ˈfeɪl.jər/', 'noun', 'thất bại', 'Failure is a lesson.', 'thất bại', 'general'],
    ['chance', '/tʃɑːns/', 'noun', 'cơ hội', 'Give me a chance.', 'cơ hội', 'general'],
    ['opportunity', '/ˌɒp.əˈtjuː.nə.ti/', 'noun', 'cơ hội', 'A good opportunity.', 'cơ hội', 'business'],
    ['choice', '/tʃɔɪs/', 'noun', 'sự lựa chọn', 'Make a choice.', 'sự lựa chọn', 'general'],
    ['decision', '/dɪˈsɪʒ.ən/', 'noun', 'quyết định', 'Make a decision.', 'quyết định', 'office'],
    ['reason', '/ˈriː.zən/', 'noun', 'lý do', 'What is the reason?', 'lý do', 'general'],
    ['purpose', '/ˈpɜː.pəs/', 'noun', 'mục đích', 'What is the purpose?', 'mục đích', 'general'],
    ['effect', '/ɪˈfekt/', 'noun', 'tác động, hiệu quả', 'The effect is clear.', 'tác động, hiệu quả', 'general'],
    ['cause', '/kɔːz/', 'noun', 'nguyên nhân', 'The cause is unknown.', 'nguyên nhân', 'general'],
    ['change', '/tʃeɪndʒ/', 'noun', 'sự thay đổi', 'I need a change.', 'sự thay đổi', 'general'],
    ['difference', '/ˈdɪf.rəns/', 'noun', 'sự khác biệt', 'What is the difference?', 'sự khác biệt', 'general'],
    ['experience', '/ɪkˈspɪə.ri.əns/', 'noun', 'kinh nghiệm', 'I have experience.', 'kinh nghiệm', 'office'],
    ['skill', '/skɪl/', 'noun', 'kỹ năng', 'Communication skill.', 'kỹ năng', 'office'],
    ['ability', '/əˈbɪl.ə.ti/', 'noun', 'khả năng', 'His ability is great.', 'khả năng', 'office'],
    ['knowledge', '/ˈnɒl.ɪdʒ/', 'noun', 'kiến thức', 'Knowledge is power.', 'kiến thức', 'general'],
    ['information', '/ˌɪn.fəˈmeɪ.ʃən/', 'noun', 'thông tin', 'I need information.', 'thông tin', 'office'],
    ['news', '/njuːz/', 'noun', 'tin tức', 'The news is good.', 'tin tức', 'general'],
    ['message', '/ˈmes.ɪdʒ/', 'noun', 'tin nhắn', 'Leave a message.', 'tin nhắn', 'office'],
    ['email', '/ˈiː.meɪl/', 'noun', 'thư điện tử', 'Send an email.', 'thư điện tử', 'tech'],
    ['document', '/ˈdɒk.jə.mənt/', 'noun', 'tài liệu', 'Sign the document.', 'tài liệu', 'office'],
    ['file', '/faɪl/', 'noun', 'tập tin', 'Save the file.', 'tập tin', 'office'],
    ['folder', '/ˈfəʊl.dər/', 'noun', 'thư mục', 'Open the folder.', 'thư mục', 'office'],
    ['copy', '/ˈkɒp.i/', 'noun', 'bản sao', 'Make a copy.', 'bản sao', 'office'],
    ['note', '/nəʊt/', 'noun', 'ghi chú', 'Take notes.', 'ghi chú', 'office'],
    ['list', '/lɪst/', 'noun', 'danh sách', 'Make a list.', 'danh sách', 'office'],
    ['form', '/fɔːm/', 'noun', 'biểu mẫu', 'Fill in the form.', 'biểu mẫu', 'office'],
    ['application', '/ˌæp.lɪˈkeɪ.ʃən/', 'noun', 'đơn, ứng dụng', 'Submit the application.', 'đơn, ứng dụng', 'office'],
    ['interview', '/ˈɪn.tə.vjuː/', 'noun', 'phỏng vấn', 'The interview is tomorrow.', 'phỏng vấn', 'hr'],
    ['position', '/pəˈzɪʃ.ən/', 'noun', 'vị trí, chức vụ', 'Apply for the position.', 'vị trí, chức vụ', 'hr'],
    ['salary', '/ˈsæl.ə.ri/', 'noun', 'lương', 'The salary is high.', 'lương', 'hr'],
    ['wage', '/weɪdʒ/', 'noun', 'tiền công', 'Hourly wage.', 'tiền công', 'hr'],
    ['income', '/ˈɪŋ.kʌm/', 'noun', 'thu nhập', 'My income is stable.', 'thu nhập', 'finance'],
    ['cost', '/kɒst/', 'noun', 'chi phí', 'The cost is high.', 'chi phí', 'finance'],
    ['price', '/praɪs/', 'noun', 'giá', 'The price is fair.', 'giá', 'finance'],
    ['discount', '/ˈdɪs.kaʊnt/', 'noun', 'giảm giá', 'Get a discount.', 'giảm giá', 'finance'],
    ['sale', '/seɪl/', 'noun', 'khuyến mãi, bán', 'The sale is on.', 'khuyến mãi, bán', 'finance'],
    ['profit', '/ˈprɒf.ɪt/', 'noun', 'lợi nhuận', 'The profit is up.', 'lợi nhuận', 'finance'],
    ['loss', '/lɒs/', 'noun', 'sự thua lỗ', 'The loss is small.', 'sự thua lỗ', 'finance'],
    ['budget', '/ˈbʌdʒ.ɪt/', 'noun', 'ngân sách', 'Stay on budget.', 'ngân sách', 'finance'],
    ['tax', '/tæks/', 'noun', 'thuế', 'Pay the tax.', 'thuế', 'finance'],
    ['bill', '/bɪl/', 'noun', 'hóa đơn', 'Pay the bill.', 'hóa đơn', 'finance'],
    ['account', '/əˈkaʊnt/', 'noun', 'tài khoản', 'Open an account.', 'tài khoản', 'finance'],
    ['bank', '/bæŋk/', 'noun', 'ngân hàng', 'Go to the bank.', 'ngân hàng', 'finance'],
    ['money', '/ˈmʌn.i/', 'noun', 'tiền', 'Save money.', 'tiền', 'finance'],
    ['cash', '/kæʃ/', 'noun', 'tiền mặt', 'Pay in cash.', 'tiền mặt', 'finance'],
    ['check', '/tʃek/', 'noun', 'séc, kiểm tra', 'Write a check.', 'séc, kiểm tra', 'finance'],
    ['card', '/kɑːd/', 'noun', 'thẻ', 'Use a card.', 'thẻ', 'finance'],
    ['order', '/ˈɔː.dər/', 'noun', 'đơn hàng, lệnh', 'Place an order.', 'đơn hàng, lệnh', 'business'],
    ['delivery', '/dɪˈlɪv.ər.i/', 'noun', 'giao hàng', 'Free delivery.', 'giao hàng', 'business'],
    ['service', '/ˈsɜː.vɪs/', 'noun', 'dịch vụ', 'Good service.', 'dịch vụ', 'business'],
    ['product', '/ˈprɒd.ʌkt/', 'noun', 'sản phẩm', 'New product.', 'sản phẩm', 'business'],
    ['market', '/ˈmɑː.kɪt/', 'noun', 'thị trường', 'The market is big.', 'thị trường', 'marketing'],
    ['advertise', '/ˈæd.və.taɪz/', 'verb', 'quảng cáo', 'Advertise the product.', 'quảng cáo', 'marketing'],
    ['customer', '/ˈkʌs.tə.mər/', 'noun', 'khách hàng', 'Happy customer.', 'khách hàng', 'business'],
    ['agree', '/əˈɡriː/', 'verb', 'đồng ý', 'I agree with you.', 'đồng ý', 'office'],
    ['disagree', '/ˌdɪs.əˈɡriː/', 'verb', 'không đồng ý', 'I disagree.', 'không đồng ý', 'office'],
    ['suggest', '/səˈdʒest/', 'verb', 'gợi ý', 'I suggest a meeting.', 'gợi ý', 'office'],
    ['accept', '/əkˈsept/', 'verb', 'chấp nhận', 'Accept the offer.', 'chấp nhận', 'business'],
    ['refuse', '/rɪˈfjuːz/', 'verb', 'từ chối', 'Refuse the gift.', 'từ chối', 'business'],
    ['offer', '/ˈɒf.ər/', 'verb', 'đề nghị', 'Offer a discount.', 'đề nghị', 'business'],
    ['invite', '/ɪnˈvaɪt/', 'verb', 'mời', 'Invite the team.', 'mời', 'office'],
    ['arrange', '/əˈreɪndʒ/', 'verb', 'sắp xếp', 'Arrange a meeting.', 'sắp xếp', 'office'],
    ['organize', '/ˈɔː.ɡə.naɪz/', 'verb', 'tổ chức', 'Organize the event.', 'tổ chức', 'office'],
    ['prepare', '/prɪˈpeər/', 'verb', 'chuẩn bị', 'Prepare the report.', 'chuẩn bị', 'office'],
    ['complete', '/kəmˈpliːt/', 'verb', 'hoàn thành', 'Complete the task.', 'hoàn thành', 'office'],
    ['finish', '/ˈfɪn.ɪʃ/', 'verb', 'kết thúc', 'Finish the work.', 'kết thúc', 'office'],
    ['start', '/stɑːt/', 'verb', 'bắt đầu', 'Start the project.', 'bắt đầu', 'office'],
    ['continue', '/kənˈtɪn.juː/', 'verb', 'tiếp tục', 'Continue the work.', 'tiếp tục', 'office'],
    ['improve', '/ɪmˈpruːv/', 'verb', 'cải thiện', 'Improve the process.', 'cải thiện', 'office'],
    ['increase', '/ɪnˈkriːs/', 'verb', 'tăng', 'Increase sales.', 'tăng', 'business'],
    ['decrease', '/dɪˈkriːs/', 'verb', 'giảm', 'Decrease costs.', 'giảm', 'business'],
    ['reduce', '/rɪˈdjuːs/', 'verb', 'giảm', 'Reduce errors.', 'giảm', 'office'],
    ['save', '/seɪv/', 'verb', 'tiết kiệm, lưu', 'Save money.', 'tiết kiệm, lưu', 'general'],
    ['spend', '/spend/', 'verb', 'tiêu', 'Spend time wisely.', 'tiêu', 'finance'],
    ['earn', '/ɜːn/', 'verb', 'kiếm được', 'Earn a salary.', 'kiếm được', 'finance'],
    ['cost', '/kɒst/', 'verb', 'trị giá', 'It costs $10.', 'trị giá', 'finance'],
    ['charge', '/tʃɑːdʒ/', 'verb', 'tính phí', 'Charge a fee.', 'tính phí', 'finance'],
    ['borrow', '/ˈbɒr.əʊ/', 'verb', 'mượn', 'Borrow money.', 'mượn', 'finance'],
    ['lend', '/lend/', 'verb', 'cho mượn', 'Lend me a pen.', 'cho mượn', 'general'],
    ['own', '/əʊn/', 'verb', 'sở hữu', 'I own a car.', 'sở hữu', 'general'],
    ['belong', '/bɪˈlɒŋ/', 'verb', 'thuộc về', 'It belongs to me.', 'thuộc về', 'general'],
    ['share', '/ʃeər/', 'verb', 'chia sẻ', 'Share the file.', 'chia sẻ', 'office'],
    ['agree', '/əˈɡriː/', 'verb', 'đồng ý', 'We agree on the plan.', 'đồng ý', 'office'],
    ['travel', '/ˈtræv.əl/', 'verb', 'đi công tác', 'I travel for work.', 'đi công tác', 'business'],
    ['arrive', '/əˈraɪv/', 'verb', 'đến', 'Arrive on time.', 'đến', 'office'],
    ['book', '/bʊk/', 'verb', 'đặt chỗ', 'Book a flight.', 'đặt chỗ', 'travel'],
    ['reserve', '/rɪˈzɜːv/', 'verb', 'đặt trước', 'Reserve a table.', 'đặt trước', 'travel'],
  ]
  B1.forEach((w) => vocabs.push(V('B1', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // ============================================================
  // B2 — UPPER-INTERMEDIATE (100 từ) — TOEIC 600-750
  // Business nâng cao, đàm phán, tài chính
  // ============================================================
  const B2 = [
    ['negotiate', '/nɪˈɡəʊ.ʃi.eɪt/', 'verb', 'đàm phán', 'Negotiate the contract.', 'đàm phán', 'business'],
    ['contract', '/ˈkɒn.trækt/', 'noun', 'hợp đồng', 'Sign the contract.', 'hợp đồng', 'business'],
    ['agreement', '/əˈɡriː.mənt/', 'noun', 'thỏa thuận', 'Reach an agreement.', 'thỏa thuận', 'business'],
    ['deal', '/diːl/', 'noun', 'thỏa thuận, giao dịch', 'Close the deal.', 'thỏa thuận, giao dịch', 'business'],
    ['partner', '/ˈpɑːt.nər/', 'noun', 'đối tác', 'Our partner is reliable.', 'đối tác', 'business'],
    ['partnership', '/ˈpɑːt.nə.ʃɪp/', 'noun', 'sự hợp tác', 'Build a partnership.', 'sự hợp tác', 'business'],
    ['collaborate', '/kəˈlæb.ə.reɪt/', 'verb', 'hợp tác', 'Collaborate with the team.', 'hợp tác', 'office'],
    ['cooperate', '/kəʊˈɒp.ə.reɪt/', 'verb', 'phối hợp', 'Cooperate on the project.', 'phối hợp', 'office'],
    ['revenue', '/ˈrev.ə.nuː/', 'noun', 'doanh thu', 'Revenue is up 10%.', 'doanh thu', 'finance'],
    ['expense', '/ɪkˈspens/', 'noun', 'chi phí', 'Track expenses.', 'chi phí', 'finance'],
    ['investment', '/ɪnˈvest.mənt/', 'noun', 'khoản đầu tư', 'Make an investment.', 'khoản đầu tư', 'finance'],
    ['invest', '/ɪnˈvest/', 'verb', 'đầu tư', 'Invest in stocks.', 'đầu tư', 'finance'],
    ['investor', '/ɪnˈves.tər/', 'noun', 'nhà đầu tư', 'Meet the investor.', 'nhà đầu tư', 'finance'],
    ['shareholder', '/ˈʃeə.həʊl.dər/', 'noun', 'cổ đông', 'The shareholder voted.', 'cổ đông', 'finance'],
    ['stock', '/stɒk/', 'noun', 'cổ phiếu, hàng tồn', 'Buy stock.', 'cổ phiếu, hàng tồn', 'finance'],
    ['share', '/ʃeər/', 'noun', 'cổ phần', 'Buy shares.', 'cổ phần', 'finance'],
    ['asset', '/ˈæs.et/', 'noun', 'tài sản', 'The asset is valuable.', 'tài sản', 'finance'],
    ['liability', '/ˌlaɪ.əˈbɪl.ə.ti/', 'noun', 'khoản nợ', 'The liability is high.', 'khoản nợ', 'finance'],
    ['capital', '/ˈkæp.ɪ.təl/', 'noun', 'vốn', 'Raise capital.', 'vốn', 'finance'],
    ['fund', '/fʌnd/', 'noun', 'quỹ', 'The fund is large.', 'quỹ', 'finance'],
    ['loan', '/ləʊn/', 'noun', 'khoản vay', 'Pay off the loan.', 'khoản vay', 'finance'],
    ['debt', '/det/', 'noun', 'khoản nợ', 'Reduce debt.', 'khoản nợ', 'finance'],
    ['interest', '/ˈɪn.trəst/', 'noun', 'lãi suất', 'Pay interest.', 'lãi suất', 'finance'],
    ['rate', '/reɪt/', 'noun', 'tỷ lệ', 'The rate is high.', 'tỷ lệ', 'finance'],
    ['exchange', '/ɪksˈtʃeɪndʒ/', 'noun', 'trao đổi, hối đoái', 'Exchange rate.', 'trao đổi, hối đoái', 'finance'],
    ['currency', '/ˈkʌr.ən.si/', 'noun', 'tiền tệ', 'Foreign currency.', 'tiền tệ', 'finance'],
    ['trade', '/treɪd/', 'noun', 'thương mại', 'International trade.', 'thương mại', 'business'],
    ['import', '/ˈɪm.pɔːt/', 'verb', 'nhập khẩu', 'Import goods.', 'nhập khẩu', 'business'],
    ['export', '/ɪkˈspɔːt/', 'verb', 'xuất khẩu', 'Export products.', 'xuất khẩu', 'business'],
    ['industry', '/ˈɪn.də.stri/', 'noun', 'ngành công nghiệp', 'The tech industry.', 'ngành công nghiệp', 'business'],
    ['manufacture', '/ˌmæn.jəˈfæk.tʃər/', 'verb', 'sản xuất', 'Manufacture goods.', 'sản xuất', 'business'],
    ['produce', '/prəˈdjuːs/', 'verb', 'sản xuất', 'Produce more.', 'sản xuất', 'business'],
    ['production', '/prəˈdʌk.ʃən/', 'noun', 'sự sản xuất', 'Increase production.', 'sự sản xuất', 'business'],
    ['productivity', '/ˌprɒd.ʌkˈtɪv.ə.ti/', 'noun', 'năng suất', 'Boost productivity.', 'năng suất', 'office'],
    ['efficient', '/ɪˈfɪʃ.ənt/', 'adj', 'hiệu quả', 'An efficient process.', 'hiệu quả', 'office'],
    ['effective', '/ɪˈfek.tɪv/', 'adj', 'có hiệu lực', 'An effective method.', 'có hiệu lực', 'office'],
    ['strategy', '/ˈstræt.ə.dʒi/', 'noun', 'chiến lược', 'A new strategy.', 'chiến lược', 'business'],
    ['strategic', '/strəˈtiː.dʒɪk/', 'adj', 'thuộc chiến lược', 'A strategic plan.', 'thuộc chiến lược', 'business'],
    ['plan', '/plæn/', 'noun', 'kế hoạch', 'A business plan.', 'kế hoạch', 'business'],
    ['policy', '/ˈpɒl.ə.si/', 'noun', 'chính sách', 'Company policy.', 'chính sách', 'office'],
    ['procedure', '/prəˈsiː.dʒər/', 'noun', 'thủ tục', 'Follow the procedure.', 'thủ tục', 'office'],
    ['process', '/ˈprəʊ.ses/', 'noun', 'quy trình', 'Improve the process.', 'quy trình', 'office'],
    ['system', '/ˈsɪs.təm/', 'noun', 'hệ thống', 'Update the system.', 'hệ thống', 'tech'],
    ['method', '/ˈmeθ.əd/', 'noun', 'phương pháp', 'A new method.', 'phương pháp', 'office'],
    ['approach', '/əˈprəʊtʃ/', 'noun', 'cách tiếp cận', 'A new approach.', 'cách tiếp cận', 'office'],
    ['solution', '/səˈluː.ʃən/', 'noun', 'giải pháp', 'Find a solution.', 'giải pháp', 'office'],
    ['issue', '/ˈɪʃ.uː/', 'noun', 'vấn đề', 'Address the issue.', 'vấn đề', 'office'],
    ['challenge', '/ˈtʃæl.ɪndʒ/', 'noun', 'thử thách', 'A big challenge.', 'thử thách', 'business'],
    ['risk', '/rɪsk/', 'noun', 'rủi ro', 'Take a risk.', 'rủi ro', 'business'],
    ['benefit', '/ˈben.ɪ.fɪt/', 'noun', 'lợi ích', 'Health benefit.', 'lợi ích', 'hr'],
    ['advantage', '/ədˈvɑːn.tɪdʒ/', 'noun', 'lợi thế', 'A big advantage.', 'lợi thế', 'business'],
    ['disadvantage', '/ˌdɪs.ədˈvɑːn.tɪdʒ/', 'noun', 'bất lợi', 'A major disadvantage.', 'bất lợi', 'business'],
    ['feature', '/ˈfiː.tʃər/', 'noun', 'tính năng', 'A new feature.', 'tính năng', 'tech'],
    ['function', '/ˈfʌŋk.ʃən/', 'noun', 'chức năng', 'The function is useful.', 'chức năng', 'tech'],
    ['quality', '/ˈkwɒl.ə.ti/', 'noun', 'chất lượng', 'High quality.', 'chất lượng', 'business'],
    ['quantity', '/ˈkwɒn.tə.ti/', 'noun', 'số lượng', 'A large quantity.', 'số lượng', 'business'],
    ['standard', '/ˈstæn.dəd/', 'noun', 'tiêu chuẩn', 'Meet the standard.', 'tiêu chuẩn', 'business'],
    ['requirement', '/rɪˈkwaɪə.mənt/', 'noun', 'yêu cầu', 'Meet the requirements.', 'yêu cầu', 'office'],
    ['demand', '/dɪˈmɑːnd/', 'noun', 'nhu cầu', 'High demand.', 'nhu cầu', 'business'],
    ['supply', '/səˈplaɪ/', 'noun', 'nguồn cung', 'Limited supply.', 'nguồn cung', 'business'],
    ['available', '/əˈveɪl.ə.bəl/', 'adj', 'có sẵn', 'Available now.', 'có sẵn', 'office'],
    ['reliable', '/rɪˈlaɪ.ə.bəl/', 'adj', 'đáng tin cậy', 'A reliable partner.', 'đáng tin cậy', 'business'],
    ['responsible', '/rɪˈspɒn.sə.bəl/', 'adj', 'chịu trách nhiệm', 'Be responsible.', 'chịu trách nhiệm', 'office'],
    ['accountable', '/əˈkaʊn.tə.bəl/', 'adj', 'có trách nhiệm giải trình', 'Be accountable.', 'có trách nhiệm giải trình', 'office'],
    ['essential', '/ɪˈsen.ʃəl/', 'adj', 'thiết yếu', 'Essential skills.', 'thiết yếu', 'office'],
    ['necessary', '/ˈnes.ə.ser.i/', 'adj', 'cần thiết', 'It is necessary.', 'cần thiết', 'office'],
    ['important', '/ɪmˈpɔː.tənt/', 'adj', 'quan trọng', 'An important meeting.', 'quan trọng', 'office'],
    ['significant', '/sɪɡˈnɪf.ɪ.kənt/', 'adj', 'đáng kể', 'A significant change.', 'đáng kể', 'office'],
    ['considerable', '/kənˈsɪd.ər.ə.bəl/', 'adj', 'đáng kể', 'Considerable effort.', 'đáng kể', 'office'],
    ['substantial', '/səbˈstæn.ʃəl/', 'adj', 'đáng kể, lớn', 'Substantial profit.', 'đáng kể, lớn', 'finance'],
    ['sufficient', '/səˈfɪʃ.ənt/', 'adj', 'đủ', 'Sufficient funds.', 'đủ', 'finance'],
    ['adequate', '/ˈæd.ɪ.kwət/', 'adj', 'đầy đủ', 'Adequate time.', 'đầy đủ', 'office'],
    ['appropriate', '/əˈprəʊ.pri.ət/', 'adj', 'thích hợp', 'An appropriate response.', 'thích hợp', 'office'],
    ['suitable', '/ˈsuː.tə.bəl/', 'adj', 'phù hợp', 'A suitable candidate.', 'phù hợp', 'hr'],
    ['relevant', '/ˈrel.ə.vənt/', 'adj', 'liên quan', 'Relevant information.', 'liên quan', 'office'],
    ['accurate', '/ˈæk.jə.rət/', 'adj', 'chính xác', 'Accurate data.', 'chính xác', 'office'],
    ['precise', '/prɪˈsaɪs/', 'adj', 'chính xác', 'A precise measurement.', 'chính xác', 'office'],
    ['exact', '/ɪɡˈzækt/', 'adj', 'chính xác', 'The exact number.', 'chính xác', 'office'],
    ['correct', '/kəˈrekt/', 'adj', 'đúng', 'The correct answer.', 'đúng', 'office'],
    ['current', '/ˈkʌr.ənt/', 'adj', 'hiện tại', 'The current situation.', 'hiện tại', 'office'],
    ['present', '/ˈprez.ənt/', 'adj', 'hiện tại', 'Present at the meeting.', 'hiện tại', 'office'],
    ['previous', '/ˈpriː.vi.əs/', 'adj', 'trước đó', 'The previous report.', 'trước đó', 'office'],
    ['former', '/ˈfɔː.mər/', 'adj', 'trước đây', 'A former colleague.', 'trước đây', 'office'],
    ['latter', '/ˈlæt.ər/', 'adj', 'sau (của 2)', 'The latter option.', 'sau (của 2)', 'office'],
    ['recent', '/ˈriː.sənt/', 'adj', 'gần đây', 'A recent study.', 'gần đây', 'office'],
    ['modern', '/ˈmɒd.ən/', 'adj', 'hiện đại', 'Modern technology.', 'hiện đại', 'tech'],
    ['traditional', '/trəˈdɪʃ.ən.əl/', 'adj', 'truyền thống', 'Traditional methods.', 'truyền thống', 'general'],
    ['conventional', '/kənˈven.ʃən.əl/', 'adj', 'thông thường', 'A conventional approach.', 'thông thường', 'office'],
    ['original', '/əˈrɪdʒ.ɪ.nəl/', 'adj', 'nguyên gốc', 'The original document.', 'nguyên gốc', 'office'],
    ['final', '/ˈfaɪ.nəl/', 'adj', 'cuối cùng', 'The final decision.', 'cuối cùng', 'office'],
    ['initial', '/ɪˈnɪʃ.əl/', 'adj', 'ban đầu', 'The initial plan.', 'ban đầu', 'office'],
    ['primary', '/ˈpraɪ.mər.i/', 'adj', 'chính, chính yếu', 'The primary goal.', 'chính, chính yếu', 'office'],
    ['secondary', '/ˈsek.ən.dər.i/', 'adj', 'thứ yếu', 'A secondary issue.', 'thứ yếu', 'office'],
    ['main', '/meɪn/', 'adj', 'chính', 'The main reason.', 'chính', 'office'],
    ['major', '/ˈmeɪ.dʒər/', 'adj', 'lớn, chính', 'A major problem.', 'lớn, chính', 'office'],
    ['minor', '/ˈmaɪ.nər/', 'adj', 'nhỏ, thứ yếu', 'A minor issue.', 'nhỏ, thứ yếu', 'office'],
    ['complex', '/ˈkɒm.pleks/', 'adj', 'phức tạp', 'A complex problem.', 'phức tạp', 'office'],
    ['simple', '/ˈsɪm.pəl/', 'adj', 'đơn giản', 'A simple solution.', 'đơn giản', 'office'],
    ['complicated', '/ˈkɒm.plɪ.keɪ.tɪd/', 'adj', 'phức tạp', 'A complicated situation.', 'phức tạp', 'office'],
    ['obvious', '/ˈɒb.vi.əs/', 'adj', 'rõ ràng', 'An obvious mistake.', 'rõ ràng', 'office'],
    ['clear', '/klɪər/', 'adj', 'rõ ràng', 'A clear explanation.', 'rõ ràng', 'office'],
    ['vague', '/veɪɡ/', 'adj', 'mơ hồ', 'A vague answer.', 'mơ hồ', 'office'],
    ['specific', '/spəˈsɪf.ɪk/', 'adj', 'cụ thể', 'Specific details.', 'cụ thể', 'office'],
    ['general', '/ˈdʒen.ər.əl/', 'adj', 'chung', 'A general idea.', 'chung', 'office'],
    ['particular', '/pəˈtɪk.jə.lər/', 'adj', 'cụ thể, riêng', 'A particular case.', 'cụ thể, riêng', 'office'],
    ['certain', '/ˈsɜː.tən/', 'adj', 'chắc chắn, nhất định', 'A certain person.', 'chắc chắn, nhất định', 'office'],
    ['able', '/ˈeɪ.bəl/', 'adj', 'có khả năng', 'Be able to do it.', 'có khả năng', 'office'],
    ['unable', '/ʌnˈeɪ.bəl/', 'adj', 'không có khả năng', 'Unable to attend.', 'không có khả năng', 'office'],
    ['capable', '/ˈkeɪ.pə.bəl/', 'adj', 'có năng lực', 'A capable leader.', 'có năng lực', 'office'],
  ]
  B2.forEach((w) => vocabs.push(V('B2', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // ============================================================
  // C1 — ADVANCED (100 từ) — TOEIC 750-900
  // Business/academic nâng cao, từ trang trọng
  // ============================================================
  const C1 = [
    ['consolidate', '/kənˈsɒl.ɪ.deɪt/', 'verb', 'hợp nhất, củng cố', 'Consolidate the departments.', 'hợp nhất, củng cố', 'business'],
    ['lucrative', '/ˈluː.krə.tɪv/', 'adj', 'có lợi, sinh lời', 'A lucrative business.', 'có lợi, sinh lời', 'finance'],
    ['pragmatic', '/præɡˈmæt.ɪk/', 'adj', 'thực dụng', 'A pragmatic approach.', 'thực dụng', 'office'],
    ['unprecedented', '/ʌnˈpres.ɪ.den.tɪd/', 'adj', 'chưa từng có', 'Unprecedented growth.', 'chưa từng có', 'business'],
    ['scrutinize', '/ˈskruː.tɪ.naɪz/', 'verb', 'xem xét kỹ', 'Scrutinize the report.', 'xem xét kỹ', 'office'],
    ['feasible', '/ˈfiː.zə.bəl/', 'adj', 'khả thi', 'A feasible plan.', 'khả thi', 'office'],
    ['mitigate', '/ˈmɪt.ɪ.ɡeɪt/', 'verb', 'giảm nhẹ', 'Mitigate the risk.', 'giảm nhẹ', 'business'],
    ['implement', '/ˈɪm.plɪ.ment/', 'verb', 'thực thi', 'Implement the strategy.', 'thực thi', 'office'],
    ['execute', '/ˈek.sɪ.kjuːt/', 'verb', 'thực hiện', 'Execute the plan.', 'thực hiện', 'office'],
    ['accomplish', '/əˈkʌm.plɪʃ/', 'verb', 'hoàn thành', 'Accomplish the goal.', 'hoàn thành', 'office'],
    ['achieve', '/əˈtʃiːv/', 'verb', 'đạt được', 'Achieve success.', 'đạt được', 'office'],
    ['attain', '/əˈteɪn/', 'verb', 'đạt được', 'Attain the target.', 'đạt được', 'office'],
    ['acquire', '/əˈkwaɪər/', 'verb', 'thu được, mua lại', 'Acquire a company.', 'thu được, mua lại', 'business'],
    ['merge', '/mɜːdʒ/', 'verb', 'sáp nhập', 'Merge with another firm.', 'sáp nhập', 'business'],
    ['acquisition', '/ˌæk.wɪˈzɪʃ.ən/', 'noun', 'sự mua lại', 'A new acquisition.', 'sự mua lại', 'business'],
    ['merger', '/ˈmɜː.dʒər/', 'noun', 'sự sáp nhập', 'A merger of equals.', 'sự sáp nhập', 'business'],
    ['venture', '/ˈven.tʃər/', 'noun', 'dự án mạo hiểm', 'A joint venture.', 'dự án mạo hiểm', 'business'],
    ['enterprise', '/ˈen.tə.praɪz/', 'noun', 'doanh nghiệp', 'A large enterprise.', 'doanh nghiệp', 'business'],
    ['corporation', '/ˌkɔː.pəˈreɪ.ʃən/', 'noun', 'tập đoàn', 'A multinational corporation.', 'tập đoàn', 'business'],
    ['subsidiary', '/səbˈsɪd.i.ər.i/', 'noun', 'công ty con', 'A subsidiary company.', 'công ty con', 'business'],
    ['affiliate', '/əˈfɪl.i.eɪt/', 'noun', 'công ty liên kết', 'An affiliate partner.', 'công ty liên kết', 'business'],
    ['franchise', '/ˈfræn.tʃaɪz/', 'noun', 'nhượng quyền', 'Open a franchise.', 'nhượng quyền', 'business'],
    ['branch', '/brɑːntʃ/', 'noun', 'chi nhánh', 'A new branch.', 'chi nhánh', 'business'],
    ['headquarters', '/ˌhedˈkwɔː.təz/', 'noun', 'trụ sở chính', 'At headquarters.', 'trụ sở chính', 'business'],
    ['division', '/dɪˈvɪʒ.ən/', 'noun', 'phòng, bộ phận', 'The sales division.', 'phòng, bộ phận', 'office'],
    ['subsidiary', '/səbˈsɪd.i.ər.i/', 'adj', 'phụ thuộc', 'A subsidiary role.', 'phụ thuộc', 'business'],
    ['allocate', '/ˈæl.ə.keɪt/', 'verb', 'phân bổ', 'Allocate resources.', 'phân bổ', 'finance'],
    ['distribute', '/dɪˈstrɪb.juːt/', 'verb', 'phân phối', 'Distribute the products.', 'phân phối', 'business'],
    ['contribute', '/kənˈtrɪb.juːt/', 'verb', 'đóng góp', 'Contribute to the project.', 'đóng góp', 'office'],
    ['attribute', '/əˈtrɪb.juːt/', 'verb', 'qui cho', 'Attribute success to hard work.', 'qui cho', 'office'],
    ['attribute', '/ˈæt.rɪ.bjuːt/', 'noun', 'đặc điểm', 'A key attribute.', 'đặc điểm', 'office'],
    ['assess', '/əˈses/', 'verb', 'đánh giá', 'Assess the situation.', 'đánh giá', 'office'],
    ['evaluate', '/ɪˈvæl.ju.eɪt/', 'verb', 'đánh giá', 'Evaluate performance.', 'đánh giá', 'hr'],
    ['analyze', '/ˈæn.əl.aɪz/', 'verb', 'phân tích', 'Analyze the data.', 'phân tích', 'office'],
    ['examine', '/ɪɡˈzæm.ɪn/', 'verb', 'xem xét', 'Examine the document.', 'xem xét', 'office'],
    ['investigate', '/ɪnˈves.tɪ.ɡeɪt/', 'verb', 'điều tra', 'Investigate the issue.', 'điều tra', 'office'],
    ['review', '/rɪˈvjuː/', 'verb', 'xem lại', 'Review the contract.', 'xem lại', 'office'],
    ['supervise', '/ˈsuː.pə.vaɪz/', 'verb', 'giám sát', 'Supervise the team.', 'giám sát', 'hr'],
    ['monitor', '/ˈmɒn.ɪ.tər/', 'verb', 'theo dõi', 'Monitor progress.', 'theo dõi', 'office'],
    ['oversee', '/ˌəʊ.vəˈsiː/', 'verb', 'giám sát', 'Oversee the project.', 'giám sát', 'office'],
    ['coordinate', '/kəʊˈɔː.dɪ.neɪt/', 'verb', 'phối hợp', 'Coordinate the event.', 'phối hợp', 'office'],
    ['facilitate', '/fəˈsɪl.ɪ.teɪt/', 'verb', 'tạo điều kiện', 'Facilitate the meeting.', 'tạo điều kiện', 'office'],
    ['administer', '/ədˈmɪn.ɪ.stər/', 'verb', 'quản lý', 'Administer the program.', 'quản lý', 'office'],
    ['regulate', '/ˈreɡ.jə.leɪt/', 'verb', 'điều chỉnh', 'Regulate the industry.', 'điều chỉnh', 'business'],
    ['comply', '/kəmˈplaɪ/', 'verb', 'tuân thủ', 'Comply with the rules.', 'tuân thủ', 'business'],
    ['adhere', '/ədˈhɪər/', 'verb', 'bám sát, tuân theo', 'Adhere to the plan.', 'bám sát, tuân theo', 'office'],
    ['conform', '/kənˈfɔːm/', 'verb', 'tuân theo', 'Conform to standards.', 'tuân theo', 'office'],
    ['authorize', '/ˈɔː.θər.aɪz/', 'verb', 'uỷ quyền', 'Authorize the payment.', 'uỷ quyền', 'office'],
    ['delegate', '/ˈdel.ɪ.ɡeɪt/', 'verb', 'giao quyền', 'Delegate the task.', 'giao quyền', 'office'],
    ['empower', '/ɪmˈpaʊər/', 'verb', 'trao quyền', 'Empower the team.', 'trao quyền', 'hr'],
    ['enable', '/ɪˈneɪ.bəl/', 'verb', 'cho phép', 'Enable the feature.', 'cho phép', 'tech'],
    ['enhance', '/ɪnˈhɑːns/', 'verb', 'nâng cao', 'Enhance the quality.', 'nâng cao', 'office'],
    ['boost', '/buːst/', 'verb', 'tăng cường', 'Boost sales.', 'tăng cường', 'business'],
    ['maximize', '/ˈmæk.sɪ.maɪz/', 'verb', 'tối đa', 'Maximize profit.', 'tối đa', 'finance'],
    ['minimize', '/ˈmɪn.ɪ.maɪz/', 'verb', 'tối thiểu', 'Minimize risk.', 'tối thiểu', 'finance'],
    ['optimize', '/ˈɒp.tɪ.maɪz/', 'verb', 'tối ưu', 'Optimize the process.', 'tối ưu', 'office'],
    ['innovate', '/ˈɪn.ə.veɪt/', 'verb', 'đổi mới', 'Innovate constantly.', 'đổi mới', 'business'],
    ['renovate', '/ˈren.ə.veɪt/', 'verb', 'cải tạo', 'Renovate the office.', 'cải tạo', 'office'],
    ['restructure', '/ˌriːˈstrʌk.tʃər/', 'verb', 'tái cấu trúc', 'Restructure the company.', 'tái cấu trúc', 'business'],
    ['downsize', '/ˈdaʊn.saɪz/', 'verb', 'giảm quy mô', 'Downsize the workforce.', 'giảm quy mô', 'hr'],
    ['streamline', '/ˈstriːm.laɪn/', 'verb', 'tinh gọn', 'Streamline operations.', 'tinh gọn', 'office'],
    ['abolish', '/əˈbɒl.ɪʃ/', 'verb', 'bãi bỏ', 'Abolish the policy.', 'bãi bỏ', 'office'],
    ['eliminate', '/ɪˈlɪm.ɪ.neɪt/', 'verb', 'loại bỏ', 'Eliminate waste.', 'loại bỏ', 'office'],
    ['eradicate', '/ɪˈræd.ɪ.keɪt/', 'verb', 'tiêu diệt', 'Eradicate poverty.', 'tiêu diệt', 'general'],
    ['erode', '/ɪˈrəʊd/', 'verb', 'xói mòn', 'Profits erode over time.', 'xói mòn', 'finance'],
    ['diminish', '/dɪˈmɪn.ɪʃ/', 'verb', 'giảm sút', 'Diminish the value.', 'giảm sút', 'office'],
    ['deteriorate', '/dɪˈtɪə.ri.ə.reɪt/', 'verb', 'xấu đi', 'Conditions deteriorate.', 'xấu đi', 'office'],
    ['fluctuate', '/ˈflʌk.tʃu.eɪt/', 'verb', 'biến động', 'Prices fluctuate.', 'biến động', 'finance'],
    ['stabilize', '/ˈsteɪ.bəl.aɪz/', 'verb', 'ổn định', 'Stabilize the market.', 'ổn định', 'finance'],
    ['sustain', '/səˈsteɪn/', 'verb', 'duy trì', 'Sustain growth.', 'duy trì', 'business'],
    ['maintain', '/meɪnˈteɪn/', 'verb', 'bảo trì, duy trì', 'Maintain the system.', 'bảo trì, duy trì', 'office'],
    ['preserve', '/prɪˈzɜːv/', 'verb', 'bảo tồn', 'Preserve the environment.', 'bảo tồn', 'general'],
    ['conserve', '/kənˈsɜːv/', 'verb', 'bảo tồn', 'Conserve energy.', 'bảo tồn', 'general'],
    ['accumulate', '/əˈkjuː.mjə.leɪt/', 'verb', 'tích lũy', 'Accumulate wealth.', 'tích lũy', 'finance'],
    ['generate', '/ˈdʒen.ə.reɪt/', 'verb', 'tạo ra', 'Generate revenue.', 'tạo ra', 'finance'],
    ['yield', '/jiːld/', 'verb', 'sinh ra, tạo ra', 'Yield a profit.', 'sinh ra, tạo ra', 'finance'],
    ['derive', '/dɪˈraɪv/', 'verb', 'nhận được từ', 'Derive from data.', 'nhận được từ', 'office'],
    ['obtain', '/əbˈteɪn/', 'verb', 'thu được', 'Obtain permission.', 'thu được', 'office'],
    ['procure', '/prəˈkjʊər/', 'verb', 'mua sắm', 'Procure materials.', 'mua sắm', 'business'],
    ['purchase', '/ˈpɜː.tʃəs/', 'verb', 'mua', 'Purchase equipment.', 'mua', 'business'],
    ['procure', '/prəˈkjʊər/', 'verb', 'mua sắm', 'Procure the supplies.', 'mua sắm', 'business'],
    ['dispose', '/dɪˈspəʊz/', 'verb', 'tiêu hủy, loại bỏ', 'Dispose of waste.', 'tiêu hủy, loại bỏ', 'office'],
    ['discard', '/dɪˈskɑːd/', 'verb', 'vứt bỏ', 'Discard old files.', 'vứt bỏ', 'office'],
    ['retain', '/rɪˈteɪn/', 'verb', 'giữ lại', 'Retain employees.', 'giữ lại', 'hr'],
    ['recruit', '/rɪˈkruːt/', 'verb', 'tuyển dụng', 'Recruit new staff.', 'tuyển dụng', 'hr'],
    ['hire', '/ˈhaɪər/', 'verb', 'thuê', 'Hire a new manager.', 'thuê', 'hr'],
    ['dismiss', '/dɪsˈmɪs/', 'verb', 'sa thải', 'Dismiss the employee.', 'sa thải', 'hr'],
    ['lay off', '/leɪ ɒf/', 'verb', 'sa thải (tạm)', 'Lay off workers.', 'sa thải (tạm)', 'hr'],
    ['resign', '/rɪˈzaɪn/', 'verb', 'từ chức', 'Resign from the job.', 'từ chức', 'hr'],
    ['retire', '/rɪˈtaɪər/', 'verb', 'nghỉ hưu', 'Retire at 65.', 'nghỉ hưu', 'hr'],
    ['promote', '/prəˈməʊt/', 'verb', 'thăng chức', 'Promote the employee.', 'thăng chức', 'hr'],
    ['demote', '/diːˈməʊt/', 'verb', 'giáng chức', 'Demote the manager.', 'giáng chức', 'hr'],
    ['transfer', '/trænsˈfɜːr/', 'verb', 'chuyển', 'Transfer to another branch.', 'chuyển', 'hr'],
    ['relocate', '/ˌriː.ləʊˈkeɪt/', 'verb', 'tái định cư', 'Relocate to Hanoi.', 'tái định cư', 'hr'],
    ['assign', '/əˈsaɪn/', 'verb', 'giao việc', 'Assign the task.', 'giao việc', 'office'],
    ['designate', '/ˈdez.ɪɡ.neɪt/', 'verb', 'chỉ định', 'Designate a leader.', 'chỉ định', 'office'],
    ['appoint', '/əˈpɔɪnt/', 'verb', 'bổ nhiệm', 'Appoint a new director.', 'bổ nhiệm', 'hr'],
    ['nominate', '/ˈnɒm.ɪ.neɪt/', 'verb', 'đề cử', 'Nominate a candidate.', 'đề cử', 'hr'],
    ['candidate', '/ˈkæn.dɪ.dət/', 'noun', 'ứng viên', 'A strong candidate.', 'ứng viên', 'hr'],
    ['applicant', '/ˈæp.lɪ.kənt/', 'noun', 'người ứng tuyển', 'A qualified applicant.', 'người ứng tuyển', 'hr'],
    ['qualification', '/ˌkwɒl.ɪ.fɪˈkeɪ.ʃən/', 'noun', 'bằng cấp, trình độ', 'Required qualifications.', 'bằng cấp, trình độ', 'hr'],
    ['certify', '/ˈsɜː.tɪ.faɪ/', 'verb', 'chứng nhận', 'Certify the document.', 'chứng nhận', 'office'],
    ['verify', '/ˈver.ɪ.faɪ/', 'verb', 'xác minh', 'Verify the information.', 'xác minh', 'office'],
    ['validate', '/ˈvæl.ɪ.deɪt/', 'verb', 'xác thực', 'Validate the data.', 'xác thực', 'office'],
    ['confirm', '/kənˈfɜːm/', 'verb', 'xác nhận', 'Confirm the appointment.', 'xác nhận', 'office'],
    ['acknowledge', '/əkˈnɒl.ɪdʒ/', 'verb', 'công nhận', 'Acknowledge the receipt.', 'công nhận', 'office'],
    ['disclose', '/dɪsˈkləʊz/', 'verb', 'tiết lộ', 'Disclose the information.', 'tiết lộ', 'office'],
    ['reveal', '/rɪˈviːl/', 'verb', 'tiết lộ', 'Reveal the truth.', 'tiết lộ', 'office'],
    ['conceal', '/kənˈsiːl/', 'verb', 'giấu giếm', 'Conceal the fact.', 'giấu giếm', 'office'],
  ]
  C1.forEach((w) => vocabs.push(V('C1', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // ============================================================
  // C2 — MASTERY (100 từ) — TOEIC 900+
  // Từ vựng chuyên sâu, trang trọng, hiếm
  // ============================================================
  const C2 = [
    ['acquiesce', '/ˌæk.wiˈes/', 'verb', 'đồng ý (miệng cười)', 'Acquiesce to the demand.', 'đồng ý (miệng cười)', 'business'],
    ['cogent', '/ˈkəʊ.dʒənt/', 'adj', 'có lý lẽ mạnh', 'A cogent argument.', 'có lý lẽ mạnh', 'office'],
    ['ephemeral', '/ɪˈfem.ər.əl/', 'adj', 'ngắn ngủi, phù du', 'Ephemeral success.', 'ngắn ngủi, phù du', 'general'],
    ['fastidious', '/fæsˈtɪd.i.əs/', 'adj', 'tỉ mỉ, khó tính', 'A fastidious client.', 'tỉ mỉ, khó tính', 'business'],
    ['iconoclast', '/aɪˈkɒn.ə.klæst/', 'noun', 'người phá bỏ truyền thống', 'An iconoclast leader.', 'người phá bỏ truyền thống', 'business'],
    ['meticulous', '/məˈtɪk.jə.ləs/', 'adj', 'cẩn thận, tỉ mỉ', 'Meticulous planning.', 'cẩn thận, tỉ mỉ', 'office'],
    ['ostensible', '/ɒsˈten.sə.bəl/', 'adj', 'bề ngoài, có vẻ', 'The ostensible reason.', 'bề ngoài, có vẻ', 'office'],
    ['pervasive', '/pəˈveɪ.sɪv/', 'adj', 'lan rộng', 'Pervasive influence.', 'lan rộng', 'business'],
    ['ubiquitous', '/juːˈbɪk.wɪ.təs/', 'adj', 'có mặt khắp nơi', 'Ubiquitous smartphones.', 'có mặt khắp nơi', 'tech'],
    ['voracious', '/vəˈreɪ.ʃəs/', 'adj', 'háu đói, khao khát', 'A voracious reader.', 'háu đói, khao khát', 'general'],
    ['acumen', '/ˈæk.jə.mən/', 'noun', 'sự nhạy bén', 'Business acumen.', 'sự nhạy bén', 'business'],
    ['acrimony', '/ˈæk.rɪ.mə.ni/', 'noun', 'sự gay gắt', 'Speak without acrimony.', 'sự gay gắt', 'office'],
    ['alacrity', '/əˈlæk.rə.ti/', 'noun', 'sự nhiệt tình', 'Accept with alacrity.', 'sự nhiệt tình', 'office'],
    ['amalgamate', '/əˈmæl.ɡə.meɪt/', 'verb', 'hợp nhất', 'Amalgamate the companies.', 'hợp nhất', 'business'],
    ['ameliorate', '/əˈmiː.li.ə.reɪt/', 'verb', 'cải thiện', 'Ameliorate conditions.', 'cải thiện', 'office'],
    ['anomaly', '/əˈnɒm.ə.li/', 'noun', 'sự bất thường', 'A statistical anomaly.', 'sự bất thường', 'office'],
    ['apocryphal', '/əˈpɒk.rɪ.fəl/', 'adj', 'không xác thực', 'An apocryphal story.', 'không xác thực', 'general'],
    ['archaic', '/ɑːˈkeɪ.ɪk/', 'adj', 'cổ xưa, lỗi thời', 'An archaic system.', 'cổ xưa, lỗi thời', 'tech'],
    ['arduous', '/ˈɑː.dju.əs/', 'adj', 'vất vả', 'An arduous task.', 'vất vả', 'office'],
    ['ascetic', '/əˈset.ɪk/', 'adj', 'khắt khe, tu khổ', 'An ascetic lifestyle.', 'khắt khe, tu khổ', 'general'],
    ['assiduous', '/əˈsɪd.ju.əs/', 'adj', 'chăm chỉ', 'An assiduous worker.', 'chăm chỉ', 'hr'],
    ['astringent', '/əˈstrɪn.dʒənt/', 'adj', 'chua chát, khắc nghiệt', 'An astringent critique.', 'chua chát, khắc nghiệt', 'office'],
    ['audacious', '/ɔːˈdeɪ.ʃəs/', 'adj', 'táo bạo', 'An audacious plan.', 'táo bạo', 'business'],
    ['austere', '/ɒsˈtɪər/', 'adj', 'nghiêm khắc, đơn sơ', 'An austere budget.', 'nghiêm khắc, đơn sơ', 'finance'],
    ['banal', '/bəˈnɑːl/', 'adj', 'sáo rỗng, tầm thường', 'A banal comment.', 'sáo rỗng, tầm thường', 'office'],
    ['bellicose', '/ˈbel.ɪ.kəʊs/', 'adj', 'hiếu chiến', 'A bellicose statement.', 'hiếu chiến', 'business'],
    ['beneficent', '/bəˈnef.ɪ.sənt/', 'adj', 'nhân từ', 'A beneficent leader.', 'nhân từ', 'office'],
    ['benevolent', '/bəˈnev.ə.lənt/', 'adj', 'nhân đạo', 'A benevolent employer.', 'nhân đạo', 'hr'],
    ['bombastic', '/bɒmˈbæs.tɪk/', 'adj', 'khoa trương', 'A bombastic speech.', 'khoa trương', 'office'],
    ['bucolic', '/bjuːˈkɒl.ɪk/', 'adj', 'đồng quê', 'A bucolic setting.', 'đồng quê', 'general'],
    ['burgeon', '/ˈbɜː.dʒən/', 'verb', 'phát triển nhanh', 'A burgeoning market.', 'phát triển nhanh', 'business'],
    ['cacophony', '/kəˈkɒf.ə.ni/', 'noun', 'tiếng ồn ào', 'A cacophony of sounds.', 'tiếng ồn ào', 'general'],
    ['callous', '/ˈkæl.əs/', 'adj', 'vô cảm', 'A callous decision.', 'vô cảm', 'office'],
    ['candor', '/ˈkæn.dər/', 'noun', 'sự thẳng thắn', 'Speak with candor.', 'sự thẳng thắn', 'office'],
    ['capricious', '/kəˈprɪʃ.əs/', 'adj', 'hay thay đổi', 'A capricious boss.', 'hay thay đổi', 'hr'],
    ['castigate', '/ˈkæs.tɪ.ɡeɪt/', 'verb', 'trừng phạt', 'Castigate the offender.', 'trừng phạt', 'office'],
    ['catalyst', '/ˈkæt.ə.lɪst/', 'noun', 'chất xúc tác', 'A catalyst for change.', 'chất xúc tác', 'business'],
    ['caustic', '/ˈkɔːs.tɪk/', 'adj', 'ăn mòn, gay gắt', 'A caustic remark.', 'ăn mòn, gay gắt', 'office'],
    ['chicanery', '/ʃɪˈkeɪ.nər.i/', 'noun', 'sự lường gạt', 'Financial chicanery.', 'sự lường gạt', 'business'],
    ['cogitate', '/ˈkɒdʒ.ɪ.teɪt/', 'verb', 'suy nghĩ kỹ', 'Cogitate on the issue.', 'suy nghĩ kỹ', 'office'],
    ['commensurate', '/kəˈmen.ʃər.ət/', 'adj', 'tương xứng', 'Pay commensurate with skill.', 'tương xứng', 'hr'],
    ['complaisant', '/kəmˈpleɪ.zənt/', 'adj', 'dễ bảo', 'A complaisant partner.', 'dễ bảo', 'business'],
    ['compliant', '/kəmˈplaɪ.ənt/', 'adj', 'tuân thủ', 'A compliant employee.', 'tuân thủ', 'office'],
    ['conciliatory', '/kənˈsɪl.i.ə.tər.i/', 'adj', 'hòa giải', 'A conciliatory gesture.', 'hòa giải', 'office'],
    ['confound', '/kənˈfaʊnd/', 'verb', 'bối rối', 'Confound the critics.', 'bối rối', 'office'],
    ['conundrum', '/kəˈnʌn.drəm/', 'noun', 'vấn đề khó', 'A financial conundrum.', 'vấn đề khó', 'finance'],
    ['copious', '/ˈkəʊ.pi.əs/', 'adj', 'nhiều', 'Copious notes.', 'nhiều', 'office'],
    ['corroborate', '/kəˈrɒb.ər.eɪt/', 'verb', 'xác nhận', 'Corroborate the story.', 'xác nhận', 'office'],
    ['credulous', '/ˈkredʒ.ə.ləs/', 'adj', 'dễ tin', 'A credulous customer.', 'dễ tin', 'business'],
    ['culpable', '/ˈkʌl.pə.bəl/', 'adj', 'có lỗi', 'A culpable employee.', 'có lỗi', 'office'],
    ['cursory', '/ˈkɜː.sər.i/', 'adj', 'hời hợt', 'A cursory glance.', 'hời hợt', 'office'],
    ['decorum', '/dɪˈkɔː.rəm/', 'noun', 'sự đứng đắn', 'Maintain decorum.', 'sự đứng đắn', 'office'],
    ['deference', '/ˈdef.ər.əns/', 'noun', 'sự tôn trọng', 'Show deference.', 'sự tôn trọng', 'office'],
    ['delineate', '/dɪˈlɪn.i.eɪt/', 'verb', 'phác họa', 'Delineate the plan.', 'phác họa', 'office'],
    ['demagogue', '/ˈdem.ə.ɡɒɡ/', 'noun', 'kẻ xúi giục', 'A demagogue leader.', 'kẻ xúi giục', 'general'],
    ['denigrate', '/ˈden.ɪ.ɡreɪt/', 'verb', 'bôi nhọ', 'Denigrate the rival.', 'bôi nhọ', 'business'],
    ['deride', '/dɪˈraɪd/', 'verb', 'chế giễu', 'Deride the proposal.', 'chế giễu', 'office'],
    ['desiccate', '/ˈdes.ɪ.keɪt/', 'verb', 'làm khô', 'Desiccate the product.', 'làm khô', 'business'],
    ['desultory', '/ˈdes.əl.tər.i/', 'adj', 'ngẫu hứng, không kế hoạch', 'A desultory attempt.', 'ngẫu hứng, không kế hoạch', 'office'],
    ['diatribe', '/ˈdaɪ.ə.traɪb/', 'noun', 'bài diễn văn công kích', 'A bitter diatribe.', 'bài diễn văn công kích', 'office'],
    ['didactic', '/daɪˈdæk.tɪk/', 'adj', 'sư phạm', 'A didactic approach.', 'sư phạm', 'general'],
    ['dilatory', '/ˈdɪl.ə.tər.i/', 'adj', 'chậm trễ', 'A dilatory tactic.', 'chậm trễ', 'office'],
    ['discern', '/dɪˈsɜːn/', 'verb', 'nhận biết', 'Discern the truth.', 'nhận biết', 'office'],
    ['disparage', '/dɪˈspær.ɪdʒ/', 'verb', 'chê bai', 'Disparage the effort.', 'chê bai', 'office'],
    ['dissemble', '/dɪˈsem.bəl/', 'verb', 'giấu giếm', 'Dissemble the facts.', 'giấu giếm', 'office'],
    ['dissonance', '/ˈdɪs.ə.nəns/', 'noun', 'sự bất hòa', 'Cognitive dissonance.', 'sự bất hòa', 'office'],
    ['dogmatic', '/dɒɡˈmæt.ɪk/', 'adj', 'giáo điều', 'A dogmatic leader.', 'giáo điều', 'office'],
    ['ebullient', '/ɪˈbʌl.i.ənt/', 'adj', 'sôi nổi', 'An ebullient personality.', 'sôi nổi', 'office'],
    ['eclectic', '/ɪˈklek.tɪk/', 'adj', 'đa dạng', 'An eclectic collection.', 'đa dạng', 'general'],
    ['effervescent', '/ˌef.əˈves.ənt/', 'adj', 'sôi nổi, phấn khởi', 'An effervescent host.', 'sôi nổi, phấn khởi', 'office'],
    ['egregious', '/ɪˈɡriː.dʒəs/', 'adj', 'trầm trọng', 'An egregious error.', 'trầm trọng', 'office'],
    ['elegy', '/ˈel.ə.dʒi/', 'noun', 'bài thơ viếng', 'An elegy to the past.', 'bài thơ viếng', 'general'],
    ['eloquent', '/ˈel.ə.kwənt/', 'adj', 'hùng biện', 'An eloquent speaker.', 'hùng biện', 'office'],
    ['emaciated', '/ɪˈmeɪ.ʃi.eɪ.tɪd/', 'adj', 'ốm yếu', 'An emaciated figure.', 'ốm yếu', 'general'],
    ['enervate', '/ˈen.ə.veɪt/', 'verb', 'làm suy nhược', 'The heat enervates me.', 'làm suy nhược', 'general'],
    ['enigmatic', '/ˌen.ɪɡˈmæt.ɪk/', 'adj', 'bí ẩn', 'An enigmatic smile.', 'bí ẩn', 'office'],
    ['ephemeral', '/ɪˈfem.ər.əl/', 'adj', 'phù du', 'Ephemeral fame.', 'phù du', 'general'],
    ['epistolary', '/ɪˈpɪs.tə.lər.i/', 'adj', 'thuộc thư từ', 'An epistolary novel.', 'thuộc thư từ', 'general'],
    ['equanimity', '/ˌek.wəˈnɪm.ə.ti/', 'noun', 'sự bình tĩnh', 'Maintain equanimity.', 'sự bình tĩnh', 'office'],
    ['equivocal', '/ɪˈkwɪv.ə.kəl/', 'adj', 'mơ hồ', 'An equivocal answer.', 'mơ hồ', 'office'],
    ['erudite', '/ˈer.ʊ.daɪt/', 'adj', 'uyên bác', 'An erudite scholar.', 'uyên bác', 'general'],
    ['esoteric', '/ˌes.əˈter.ɪk/', 'adj', 'khó hiểu, bí truyền', 'Esoteric knowledge.', 'khó hiểu, bí truyền', 'general'],
    ['esthetic', '/iːsˈθet.ɪk/', 'adj', 'thẩm mỹ', 'An esthetic design.', 'thẩm mỹ', 'general'],
    ['eulogy', '/ˈjuː.lə.dʒi/', 'noun', 'lời điếu văn', 'Deliver a eulogy.', 'lời điếu văn', 'general'],
    ['euphemism', '/ˈjuː.fə.mɪ.zəm/', 'noun', 'l nói giảm nói tránh', 'A polite euphemism.', 'l nói giảm nói tránh', 'office'],
    ['exacerbate', '/ɪɡˈzæs.ər.beɪt/', 'verb', 'làm trầm trọng', 'Exacerbate the problem.', 'làm trầm trọng', 'office'],
    ['exculpate', '/ˈek.skʌl.peɪt/', 'verb', 'tội lỗi', 'Exculpate the accused.', 'tội lỗi', 'office'],
    ['exigency', '/ˈek.sɪ.dʒən.si/', 'noun', 'tình thế khẩn cấp', 'An unexpected exigency.', 'tình thế khẩn cấp', 'office'],
    ['extraneous', '/ɪkˈstreɪ.ni.əs/', 'adj', 'thừa, ngoài lề', 'Extraneous details.', 'thừa, ngoài lề', 'office'],
    ['fastidious', '/fæsˈtɪd.i.əs/', 'adj', 'tỉ mỉ', 'A fastidious editor.', 'tỉ mỉ', 'office'],
    ['fatuous', '/ˈfætʃ.u.əs/', 'adj', 'ngu ngốc', 'A fatuous remark.', 'ngu ngốc', 'office'],
    ['fawning', '/ˈfɔː.nɪŋ/', 'adj', 'nịnh bợ', 'A fawning subordinate.', 'nịnh bợ', 'office'],
    ['felicitous', '/fəˈlɪs.ɪ.təs/', 'adj', 'thích hợp', 'A felicitous phrase.', 'thích hợp', 'office'],
    ['ferret', '/ˈfer.ɪt/', 'verb', 'lùng sục', 'Ferret out the truth.', 'lùng sục', 'office'],
    ['fervent', '/ˈfɜː.vənt/', 'adj', 'nồng nhiệt', 'A fervent supporter.', 'nồng nhiệt', 'office'],
    ['fervid', '/ˈfɜː.vɪd/', 'adj', 'nồng nhiệt', 'A fervid imagination.', 'nồng nhiệt', 'general'],
    ['flagrant', '/ˈfleɪ.ɡrənt/', 'adj', 'trắng trợn', 'A flagrant violation.', 'trắng trợn', 'office'],
    ['flippant', '/ˈflɪp.ənt/', 'adj', 'lếch thếch', 'A flippant response.', 'lếch thếch', 'office'],
    ['foment', '/fəʊˈment/', 'verb', 'xúi giục', 'Foment rebellion.', 'xúi giục', 'general'],
    ['forestall', '/fɔːˈstɔːl/', 'verb', 'ngăn chặn trước', 'Forestall the problem.', 'ngăn chặn trước', 'office'],
    ['fortuitous', '/fɔːˈtjuː.ɪ.təs/', 'adj', 'ngẫu nhiên (tốt)', 'A fortuitous meeting.', 'ngẫu nhiên (tốt)', 'office'],
    ['fractious', '/ˈfræk.ʃəs/', 'adj', 'hay cãi cùn', 'A fractious team.', 'hay cãi cùn', 'office'],
    ['fraught', '/frɔːt/', 'adj', 'đầy rẫy', 'A fraught situation.', 'đầy rẫy', 'office'],
    ['furtive', '/ˈfɜː.tɪv/', 'adj', 'lén lút', 'A furtive glance.', 'lén lút', 'office'],
    ['garrulous', '/ˈɡær.ə.ləs/', 'adj', 'líu lo, nhiều chuyện', 'A garrulous colleague.', 'líu lo, nhiều chuyện', 'office'],
    ['germane', '/dʒɜːˈmeɪn/', 'adj', 'liên quan', 'A germane point.', 'liên quan', 'office'],
    ['grandstand', '/ˈɡrænd.stænd/', 'verb', 'diễn kịch', 'Grandstand for the crowd.', 'diễn kịch', 'office'],
    ['gregarious', '/ɡrɪˈɡeə.ri.əs/', 'adj', 'ưa giao tiếp', 'A gregarious host.', 'ưa giao tiếp', 'office'],
    ['guile', '/ɡaɪl/', 'noun', 'sự xảo quyệt', 'Act with guile.', 'sự xảo quyệt', 'office'],
    ['gullible', '/ˈɡʌl.ə.bəl/', 'adj', 'dễ bị lừa', 'A gullible victim.', 'dễ bị lừa', 'general'],
    ['harangue', '/həˈræŋ/', 'verb', 'hét vào mặt', 'Harangue the audience.', 'hét vào mặt', 'office'],
  ]
  C2.forEach((w) => vocabs.push(V('C2', w[0], w[1], w[2], w[3], w[4], w[5], w[6])))

  // Insert all vocab
  for (const v of vocabs) {
    await db.vocab.upsert({ where: { id: v.id }, update: v, create: v })
  }

  // Delete ALL old vocabs (those without a CEFR level or that are duplicates not in our list)
  const validIds = new Set(vocabs.map((v) => v.id))
  const allVocabs = await db.vocab.findMany({ select: { id: true } })
  const toDelete = allVocabs.filter((v) => !validIds.has(v.id)).map((v) => v.id)
  if (toDelete.length > 0) {
    console.log(`  Deleting ${toDelete.length} old/duplicate vocabs...`)
    await db.vocab.deleteMany({ where: { id: { in: toDelete } } })
  }

  console.log('Vocab by level seed complete.')
  console.log(`  Total: ${await db.vocab.count()}`)
  for (const level of ['A0', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2']) {
    console.log(`  ${level}: ${await db.vocab.count({ where: { level } })}`)
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
